components/dirigeants-section/entreprise-individuelle.tsx
L'abréviation pour "Monsieur" est `M.` et non `Mr`
https://fr.wikipedia.org/wiki/Monsieur
> Monsieur est abrégé en « M. ». Anciennement on trouvait Mr .
=> Abréviation pour Monsieur

components/immatriculations/summary.tsx
=> fix: add missing spaces in immatriculations/summary

pages/api/inpi-pdf-proxy/[slug].ts
Remove direct download as it : 
- often fails
- when fails it uses a thread for up to 30 seconds, therefore it threatens the application stability
It is replaced with a default redirection to INPI pdf, with no auth
=> feature: remove pdf direct download

models/tva.ts
Remove the two sentry warning use to get rough stats on VIES API and TVA numbers
=> fix: remove tva counter warning

components/title-section/index.tsx
Use an object instead of hardcoding tabs in jsx.
It will now be much easier to customize tabs based on uniteLegale type for instance
=> Refacto: move tabs into an object rather than jsx

.github/workflows/pre-merge.yml
axe-core is frequently broken because at every new version of chrome, it needs to bump its chromedriver dependency : 
https://www.npmjs.com/package/@axe-core/cli
https://github.com/dequelabs/axe-core-npm/blob/develop/packages/cli/package.json
Current chromedriver version is 106 in package.json
Current stable chrome release used in github action : 108
I suggest we wait for axe-copre to update its dependencies as it is not a crucial step of our CI
=> Tmp : disable a11y in CI

components/search-filters/filter-geo.tsx, components/search-filters/filter.tsx, components/search-filters/index.tsx, utils/helpers/debounce.ts
Alternative to `react-select` of geo filter. Only apply to Geo filters. React-select seems perfect for NAF/APE selection
Pros :
- easier to fix / tweak
- comply with dsfr and Jeremie's mock up
Cons
- not a lib
- specific to geo search
=> chore: delete advanced search js

.github/ISSUE_TEMPLATE/bug_report.md
- Zones impactées : ISSUE TEMPLATE GITHUB.
- Détails :
- Vous n'avez pas changé l'assignee par défaut sur l'issue template utilisé pour l'api de recherche. Les nouvelles issues me sont donc automatiquement assignées.
=> ops: change default issue assignee

clients/routes.ts
Include COM and DROM (drom was already working)
closes #574
=> fix: include COM in geo search

.vscode/settings.json, pages/api/ping/[slug].ts
- Zones impactées : `pages/api/ping/[slug].ts`.
- Détails : 
> [feat: use 500 in route api/ping/XXX](https://github.com/etalab/annuaire-entreprises-site/commit/0d073fa2582a04d9879c546b4faca0a96bc78be1)
4XX and 5XX errors are directly interpreted semantically by Baleen
and Uptime Robot resulting in new bugs.
fix https://github.com/etalab/annuaire-entreprises-site/issues/631
=> feat: use 500 in route api/ping/XXX

pages/donnees/api.tsx
Add an auto refresh as montoring gets updated every minute, but you currently need to reload manually to get an update on monitorings.
https://annuaire-entreprises.data.gouv.fr/donnees/api
closes #708
=> feat: reload api monitoring page every minute to refresh monitors

pages/api/data-fetching/geo/[slug].ts
antiBot seems unnecessary here : 
- API Geo access is not limited (token or rate limit) -> no need to protect it
- `/rechercher` page can stay open for a long time and filter is manually triggered thus antiBot logic is defeated
=> feat: remove anti bot from GEO

components/meta/index.tsx
Instead of using constant basepath site URL. 
Cf https://ogp.me/#metadata
Should 
fix #718 
fix #716 
fix #673
=> fix: og bug by using canonical url

components/banner/browser-is-outdated.tsx, components/layouts/layout-default.tsx, components/layouts/layout-search.tsx, components/layouts/layout-simple.tsx, package-lock.json, package.json, pages/_app.tsx, pages/faq/parcours.tsx, pages/formulaire/merci.tsx, pages/formulaire/nps.tsx, pages/index.tsx, pages/lp/[slug].tsx, pages/rechercher/carte.tsx, pages/rechercher/erreur.tsx, pages/rechercher/index.tsx, utils/server-side-props-helper/post-server-side-props.ts
This PR refactor the BrowserIsOutdatedBanner component from the layouts component into the generic one in _app.tsx
It also changes the message to present what is working instead of what is not.
- investigate why the warning message is displayed for IE 11 and not for firefox < 65 in prod only (it works in local and in preview apps)
=> refactor: move BrowserIsOutdatedBanner from layout

components/banner/browser-is-outdated.tsx
Work on several errors encountered in prod 
FF<60  & FF 60
- `SyntaxError: missing ( before catch`
-  `ReferenceError: getElementById is not defined`
=> chore: work on retro compatibility for script

clients/recherche-entreprise/index.ts, clients/recherche-entreprise/interface.ts, components/etablissement-section/index.tsx, models/etablissement.ts, models/unite-legale.ts, utils/helpers/formatting/codes-effectifs.ts
L'API de l'INSEE n'est plus appelée que dans les cas suivants : 
- La nature juridique est une entreprise individuelle, il faut vérifier si elle est diffusible
- L'unité légale a plus de 10 établissements, la pagination des établissements ne fonctionne pas sur l'api de recherche
Bonus
- Quelques champs sont manquants dans l'API de recherche p/r au retour INSEE (cf  https://github.com/etalab/annuaire-entreprises-search-api/issues/310)
Le nombre d'établissement à partir duquel on appel l'insee est arbitraire : 10. Quel est la bonne valeur à mettre ?
=> Stop calling insee unless absolutely needed

sentry.client.config.ts, sentry.server.config.ts
I see no reason to not decrease further the APM sampling : 
- it endanger the sentry instance
- the sheer volume of request make it still relevant at 0.5%
=> feat: decrease sampling even further to 0.5%

models/etablissement.ts, pages/carte/[slug].tsx
When etablissement comes from `RechercheEntreprise` no need to call BAN again
=> refacto: dont call ban when there already is a geoloc

components/annonces-section/annonces-association.tsx, components/annonces-section/bodacc.tsx, components/annonces-section/comptes-association.tsx, components/dirigeants-section/beneficiaires.tsx, components/dirigeants-section/rne-dirigeants.tsx, components/error-boundary/index.tsx, components/header/index.tsx, components/layouts/layout-default.tsx, components/layouts/layout-search.tsx, components/layouts/layout-simple.tsx, components/unite-legale-page-link/index.tsx, hooks/use-session.ts, pages/_app.tsx, pages/dirigeants/[slug].tsx, pages/entreprise/[slug].tsx, pages/faq/parcours.tsx, pages/index.tsx, pages/rechercher/carte.tsx, pages/rechercher/erreur.tsx, pages/rechercher/index.tsx
- create a new component UniteLegalePageLink
- use it in the dirigeants and annonces sections
- add a `useSession` hook to get the session from anywhere
fix #720
=>  feat: add unite legale name to link label 

clients/sirene-insee/siren.ts, components-ui/alerts/association-adress.tsx, components-ui/alerts/association-creation-not-found-alert.tsx, components/annonces-section/annonces-association.tsx, components/annonces-section/comptes-association.tsx, components/association-section/index.tsx, components/finances-section/association/index.tsx, components/immatriculations/index.tsx, components/title-section/index.tsx, components/title-section/tabs.tsx, hooks/fetch/comptes-association.ts, hooks/fetch/joafe.ts, models/index.ts, models/unite-legale.ts, pages/annonces/[slug].tsx, pages/donnees-financieres/[slug].tsx, pages/entreprise/[slug].tsx
close #728 
Fllowing @johangirod new sentry setup I noticed a lot of 429 from RNA get trigger on etablissement page where data from RNA is not used !
I propose to uncouple RNA from uniteLegale construction and make it a dedicated data source.
I also cleaned the financeAssoSection, not used since RNA remove association finances from its payload and move the adress warning into the RNA section as it is more relevant there.
This should significantly reduce 429
=> Revamp RNA architecture

frontend/src/fetch-tva.js
Unsure what to do here when `FetchRessourceException is not defined`
https://errors.data.gouv.fr/organizations/sentry/issues/131620/?project=16&query=is%3Aunresolved&referrer=issue-stream
I think it is dangerous to share code between vite and react. I would advise using a custom exception here. 
I would be more confortable if you handle it from here @johangirod
=> fix: fetch resource exception is not defined

components/etablissement-liste-section/index.tsx, components/non-diffusible/index.tsx, models/unite-legale.ts, pages/annonces/[slug].tsx, pages/dirigeants/[slug].tsx
Follow up of two support tickets : 
- protected siren and non-diffusible now also apply to BODACC (also discussed with the SPM's DPD)
- protected siren apply to its etablissements (that was more of a bug)
=> feat: hide bodacc for protected siren

components/espace-agent-components/documents/actes.tsx, components/espace-agent-components/documents/bilans.tsx, pages/donnees-financieres/[slug].tsx, utils/network/frontend/index.ts
Pretty big regression here : 
Section would rely on status to display `NotFoundInfo` and FailToFetchError would hide it compared to previous HttpErrors
I think this need a further investigation to ensure that no other part of the app using similar logic could be impacted  @johangirod
=> fix: failed to fetch exception erasing the status is breaking section polymorphism

components-ui/alerts/association-adress.tsx, components-ui/badge/frequent.tsx, components-ui/badge/index.tsx, components-ui/filter-menu/filter-menu.tsx, components/banner/info-banner.tsx, components/conventions-collectives-section/index.tsx, components/dirigeants-section/elus-section.tsx, components/etablissement-liste-section/index.tsx, components/labels-and-certificates/bio/index.tsx, components/labels-and-certificates/entrepreneur-spectacles/index.tsx, components/non-renseigne/index.tsx, components/search-results/results-counter.tsx, components/search-results/results-list.tsx, components/table/simple.tsx, frontend/style/globals.css
- sort by role (maire first, then by adjoint number, then by name)
- display date of birth separately
- add « non renseigné » when role is not provided
Considering doing the same for `dirigeant` section, what do you think?
closes #549
=> feat: improve elus section

pages/api/data-fetching/espace-agent/documents/[slug].tsx, pages/api/data-fetching/espace-agent/documents/download/[slug].tsx, pages/api/data-fetching/rne/[slug].ts
@johangirod I think this was introduced in the last bump package PR
=> fix: missing default export breaks the actes routes

components-ui/button-agent-connect/index.tsx, components/header/index.tsx, cypress/e2e/data-fetching.cy.js, frontend/src/load-bar.js, hooks/use-path-from-router.ts, pages/api/auth/agent-connect/callback.ts, utils/session/with-anti-bot.ts
Several improvements over current agent login cinematic : 
- add the most basic tests on data-fetching routes
- fix `pathFrom` logic
- fix an anti-bot bug 
- fix an UX issue with the logout menu
- add a gradient on load bar (we have priorities here)
=> test: add basic data-fetching routes tests

components/section/data-section-loader.tsx
Tiny update to the slow service message as some user dont understand that the it is the administration and not the website that is slow.
=> content: better slow API message that name the faulty administration

clients/open-data-soft/clients/annuaire-service-public/index.ts, components/dirigeants-section/responsables-service-public.tsx, models/service-public/index.ts
=> fix: formatting when missing dirigeant name in service-public

components/banner/nps.tsx, components/layouts/layout-connexion.tsx
Use the same yellow as the agent illu for the NPS banner and for connexion pages' background
Not sure about the connexion background
What do you think ?
=> style: generalize #fef6e3 as only light yellow accross site

clients/api-entreprise/client.ts, clients/api-entreprise/conformite/fiscale.ts, clients/api-entreprise/conformite/msa.ts, clients/api-entreprise/conformite/vigilance.ts, clients/recherche-entreprise/index.ts, clients/recherche-entreprise/interface.ts, components/unite-legale-section/index.tsx, models/core/types.ts, models/espace-agent/donnees-restreintes-entreprise.ts, pages/_error.tsx, pages/api/auth/agent-connect/callback.ts, pages/api/data-fetching/espace-agent/conformite/[slug].tsx, pages/api/data-fetching/espace-agent/documents/download/[slug].tsx, utils/session/index.ts
Not best practise, but this is a mix of fixes. Each commit can be read indendantly
- change the way we log server error in order to be able to read them in Kibana
- handle >4MB actes & bilans
- we should probably move to a dedicted service that would download files and handles queues
- @MKCG 
- date fermeture
- recipient siret to API Entreprise
=> Pasta salad

.github/workflows/deploy-cluster.yml
Up until now, when an error occured during the deployment, it was not reported in the Github action. This was due to the presence of the pipe that was sending both the stdout & the stderr to the tee command.
---
expected : 
```
/usr/bin/docker
success
```
actual : 
```
/usr/bin/docker
success
```
```sh
ssh annuaire-entreprises-staging-www-1 'which docker | tee --append /tmp/debug_err' && echo 'success' || echo 'error' 
```
---
expected : 
```
/usr/bin/docker
success
```
actual : 
```
/usr/bin/docker
success
```
```sh
ssh annuaire-entreprises-staging-www-1 'which docker 1> >(tee --append /tmp/debug_err)' && echo 'success' || echo 'error'
```
---
expected : "error"
actual : "success"
```sh
ssh annuaire-entreprises-staging-www-1 'which foobar | tee --append /tmp/debug_err' && echo 'success' …
```
=> chore: the SSH command exit status is always forwarded to the executor

pages/partager/index.tsx
- Zones impactées : `pages/partager/index.tsx`.
- Détails :
- Lien vers 'status des api' renvoie vers "/administration" au lieu de "/donnees/api" sur la page partagée
- Notes :
- Le lien "/donnes" renvoie une erreur 404
- Je cherche une alternance à Montpellier/à distance si vous êtes intéressé...
=> [fix] wrong link in "partager"

components/meta/meta-server.tsx
Cf : https://github.com/vercel/next.js/issues/43914
references #947
=> fix: prevent safari from interpreting phone

components/load-bar/index.tsx, components/title-section/tabs/TabLink.tsx, components/title-section/tabs/index.tsx, components/title-section/tabs/styles.module.css
should fix a lot of ChunkLoadError in production
fix #969
=> feat: use next Link component in tab

utils/helpers/formatting/metadata/codes-NAF-rev-2.ts
- Correction d'un bug | Changement mineur.
- Zones impactées : `utils/helpers/formatting/metadata/codes-NAF-rev-2.ts`.
- Détails :
- Correction d’une **faute de frappe** (une virgule en trop) dans un des libellés de la NAFv2 (Nomenclature d’Activités Française).
- Une page où la faute apparaît : https://annuaire-entreprises.data.gouv.fr/entreprise/l-oreal-interbeauty-632012100
Le message du commit :
> Label for NAFv2 code 77.40Z was :
> « Location-bail de propriété intellectuelle et de produits similaires, à l’exception des œuvres soumises **à ,copyright** »  
> Notice the superfluous comma before «copyright».
> 
> This commit removes that comma. 
> 
> References:
> 
> - https://www.insee.fr/fr/metadonnees/nafr2/sousClasse/77.40z : has the correct label 
> - …
=> fix: typo in codes-NAF-rev-2.ts

app/not-found.tsx
@johangirod I feel this is better than current default page https://annuaire-entreprises.data.gouv.fr/sources-de-donnees
I think the same should be done for 500 but I did not fully understand how global-error.tsx and other error.tsx interacts and I dont want to break it
=> feat: create a not found default page

pages/a-propos/stats.tsx, utils/integrations/grist.ts
Bug report : 23/09 
- GRIST stopped taking new calls, returns 429 and `{"error": "Too many backlogged requests for document XXXXXX - try again later?}` on any route/resource
- 797a190e027dd7792be40c904959832d87916285 stopped log connexion on `Logs_connexion`
- 2eec0b81c1ebe89505d04976a26f57d142c6dce9 stopped ALL call (read/write) to grist
- GRIST still blocked at `Too many backlogged requests for document `
=> Revert "fix: stop calling grist"

clients/sirene-insee/helpers.ts, clients/sirene-insee/siren.ts
- Correction d'un bug
- Zones impactées : `./models/core/unite-legal.ts`.
- Détails :
- Nettoyage à la volée de la mention "suppression du nom commercial"
closes #1228
=> fix: suppression insee et recherche entreprise nom commercial

components-ui/button-pro-connect/index.tsx
- Zones impactées : `./components-ui/button-pro-connect/index.tsx`.
- Détails :
- Add a link to "Qu'est-ce que ProConnect" following this instructions : https://github.com/numerique-gouv/proconnect-documentation/blob/main/doc_fs/bouton_proconnect.md (NB : the new CSS was already in the codebase)
Closes #1236
=> feat: add link Qu'est-ce que ProConnect

app/(header-default)/lp/agent-public/page.tsx
- Zones impactées : `./app/(header-default)/lp/agent-public/page.tsx`.
- Détails :
- Hide the ProConnect button when a user is connected and replace it with a message that informs with which email we are connected
Closes #1219
=> feat: hide button ProConnect when logged in

app/(header-default)/lp/agent-public/page.tsx, components-ui/button-pro-connect/index.tsx, components/espace-agent-components/agent-wall/index.tsx, components/header/header-app-router.tsx, components/header/header-core/index.tsx, components/header/header-page-router.tsx, components/header/menu/espace-agent-link.tsx, components/header/menu/index.tsx, hooks/use-path-server.ts, middleware.ts, pages/api/auth/agent-connect/login.ts, pages/api/auth/agent-connect/logout.ts
- Correctif
- Zones impactées : `./middleware.ts`.
- Détails :
- The usePathServer hook has been removed.
- login : The middleware is now responsible for adding the pathFrom param when navigating to the "espace agent" page
- logout : referer is directly used from the route to determine the pathFrom param
#1220
=> fix: good redirect after agent public login

app/(header-default)/justificatif-immatriculation-pdf/[slug]/page.tsx, components/feedback-modal/feedback-form.tsx, components/footer/index.tsx
- Zones impactées : `multiple files`.
- Détails :
- Suppression lien Linkedin
- voire même -> voire
- mon-entreprise -> mon-entreprise.urssaf
Closes #1251
=> chore: update link, remove linkedin link and fix typo

.eslintrc, app/(header-default)/carte/[slug]/page.tsx, app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/dirigeant-content.tsx, app/(header-default)/lp/agent-public/page.tsx, utils/server-side-helper/app/get-session.ts
- Zones impactées : `multiples`.
- Détails :
- Suppression d'un warning en dev mode côté serveur : la session était une classe (IronSession) et puisque les méthodes ne pouvent pas être communiquées de serveur à client, il y avait constamment une erreur. Solution proposée : transformer la classe en objet.
- Suppression d'un warning en dev mode côté client : "key" nécessaire dans un tableau
- Suppression de la règle ESLint sur les imports : Prettier réorganisait les imports en contradiction avec la règle ESLint
Sur (quasiment toutes les pages) :
Sur cette page :
http://localhost:3000/dirigeants/552032534
=> fix: remove warnings

hooks/fetch/download-pdf.ts
- Correction d'un bug
- Zones impactées : `https://annuaire-entreprises.data.gouv.fr/justificatif-immatriculation-pdf/***`.
- Détails :
- le siren de la poste affiche "introuvable" au lieu d'"echec"
=> fix: la poste pdf incorrectly cast as 404

app/(header-default)/faq/parcours/_components/parcours-questions.tsx, models/user/helpers.ts
- Zones impactées : `parcours-questions.tsx`.
- Détails :
- auto select agent
- rename variables from previous PR
=> feat: auto select agent, use enum and rename variables

app/(header-default)/annonces/[slug]/_components/observations-rne.tsx, app/(header-default)/dirigeants/[slug]/_component/sections/association/dirigeants.tsx, app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/beneficiaires/agent-section.tsx, app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/index.tsx, app/(header-default)/documents/[slug]/_components/actes/associations.tsx, app/(header-default)/documents/[slug]/_components/actes/rne.tsx, app/(header-default)/documents/[slug]/_components/carte-professionnelle-TP-section.tsx, app/(header-default)/donnees-financieres/[slug]/_components/bilans.tsx, app/api/data-fetching/[...slug]/route.ts, app/api/data-fetching/get-beneficiaires-controller.ts, app/api/data-fetching/routes-handlers.ts, app/api/data-fetching/routes-paths.ts, app/api/data-fetching/routes-scopes.ts, app/api/data-fetching/utils.ts, components/association-section/index.tsx, components/badges-section/labels-and-certificates/protected-certificats.tsx, components/eori-cell/index.tsx, components/espace-agent-components/certifications/opqibi-section.tsx, components/espace-agent-components/certifications/qualibat-section.tsx, components/espace-agent-components/certifications/qualifelec-section.tsx, components/espace-agent-components/conformite-section.tsx, components/finances-section/association/index.tsx, components/subventions-association-section/index.tsx, components/tva-cell/index.tsx, hooks/fetch/use-API-route-data.ts
- Zones impactées : `./app/api`.
- Détails :
- Création d'une enum pour lister les chemin (paths) des routes
Même si typescript prévenait la possibilité de mal écrire une route, l'utilisation d'une enum évite de faire de copier/coller et permet d'utiliser l'autocomplétion.
Aussi et surtout, lorsqu'un chemin (path) est ajouté au fichier routes-paths, nous sommes désormais obligé de définir un scope pour cette route (sinon il y a une erreur typescript).
Enfin, 'espace-agent/beneficiaires' utilisait une variable dédiée, ce qui n'est plus nécessaire grâce à cette enum.
Closes #1288
=> Refacto routes roles handles

.github/workflows/deploy-cluster-full.yml, .github/workflows/deploy-cluster-staging.yml
Split `deploy-cluster` action into two distinct actions
- `deploy-cluster-full` : triggered with a cron, once a day or triggered manually, complete deployment 
- `deploy-cluser-staging` : triggered with a push in main, only deploy to staging
=> chore: split deployment github action

next.config.js, package-lock.json, package.json
- Zones impactées : `next.config.js`.
- Détails :
- Could fix some chunk load errors
Need to be discussed.
Details from the doc of `next-build-id` :
> Why?
> If you're running multiple instances of your app sitting behind a load balancer without session affinity (and you're building your app directly on each production server instead of pre-packaging it), a tool like this is necessary to avoid Next.js errors like ["invalid build file hash"](https://github.com/zeit/next.js/blob/52ccc14059673508803f96ef1c74eecdf27fe096/server/index.js#L444), which happens when the same client (browser code) talks to multiple server backends (Node server) that have different build ids.
> 
> The build id used by your app is stored on the file system in a BUILD_ID text file in your build …
=> fix: add generateBuildId in next.config.js

next.config.js
- Zones impactées : `next.config.js`.
- Détails :
- Fallback pour scalingo pour le generateBuildId
=> fix: scalingo predeploy

components/justificatifs/data-inpi-link/index.tsx
- Détails :
- Suppression de la balise no follow du bouton "Télécharger le justificatif d'immatriculation"
Closes https://github.com/annuaire-entreprises-data-gouv-fr/seo/issues/13
=> fix: remove nofollow attribute to button

clients/geo/communes.ts
- Zones impactées : `clients/geo/communes.ts`.
- Détails :
- Remplacement du terme **ville** par **commune** pour les filtres de recherche, à mon sens plus adapté car le terme englobe les villages.
=> Proposition de remplacement **ville** → **commune**

next.config.js
- Ajout d'un header sur les chunk loads
Ajout d'un header sur les chunk loads pour identifier sur quelle instance et sur quel build (en utilisant la date de build) a été créé une réponse.
Cela permettra d'identifier si il y a un problème de mise en cache au niveau de l'infra.
=> feat: add header to debug chunk load

next.config.ts
- Zones impactées : `next.config.ts`.
- Détails :
- Upload des sources maps non silencieux pour debug
- Utilisation de la fonctionnalité "release"
- Suppression de commentaires devenus inutiles grâce à Typescript
=> chore: disable silent, add release config and remove useless lines

next.config.ts
- Détails :
- désactivage des fonctionnalités de sentry au build time quand errors.data.gouv.fr est hors ligne
=> fix: disable all sentry build options when errors is down

app/(header-connexion)/connexion/habilitation/administration-inconnue/page.tsx, app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/dirigeants-open/content.tsx, app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/dirigeants-open/section.tsx, app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/dirigeants-protected/content.tsx, app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/dirigeants-protected/section.tsx, app/(header-default)/dirigeants/[slug]/page.tsx, app/(header-default)/labels-certificats/[slug]/page.tsx, app/api/auth/agent-connect/callback/route.ts, clients/api-entreprise/client.ts, utils/session/index.ts
- refactor lightly dirigeants components
- add a link to espace agent from dirigeant open
- add dedicated Administration Inconnue page
- prevent from calling API Entreprise when no siren
- force a reset of session as we now need to have a siret
- fix bug in CIBTP and CNETP rights generating 429
=> feat: follow up proConnect/agentConnect deployment

app/(header-default)/a-propos/stats/page.tsx, app/(header-default)/donnees/api/page.tsx
NB : Wont use unstable cache on cachedGetUniteLegale as it is an unstable API that might trigger a memory leak
Also unitelegale are cached on API Recherche redis
=> fix: network calls not cached

.github/workflows/deploy-cluster-staging.yml
This PR processes #1387
- Zones impactées : `.github/workflows/deploy-cluster-staging.yml`.
- Détails :
- Cancel the staging deployment if the workflow has been triggered by a new push
=> ci: manage concurrency for staging deployment workflow #1387

app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/dirigeants-protected/content.tsx
=> fix: remove useless comma

next.config.ts
As suggested by @ad2ien, writing security headers on site side allow dev to have much more control on POST routes and cross domain calls.
The alternative is to write them at nginx level and have every headers at the same place. @MKCG @rmonnier9 @ad2ien what do you think ? 
closes https://github.com/orgs/annuaire-entreprises-data-gouv-fr/projects/1/views/1?pane=issue&itemId=84349585&issue=annuaire-entreprises-data-gouv-fr%7Cinfrastructure%7C234
=> chore: add security headers on site side rather than infra

app/(header-minimal)/formulaire/nps/page.tsx, app/api/feedback/nps/route.ts
- Détails :
- Le ternaire sur "text" est retiré car toujours vrai
- Correction du lien canonique de /formulaire/nps 
- Suppression du lien injecté qui ne fonctionne pas sur tchap :
=> fix: remove injected link

clients/api-inclusion/index.ts, clients/monitoring/index.ts, clients/routes.ts, cypress/fixtures/up-down-io.json, cypress/mocks/handlers/up-down-io.ts, cypress/mocks/routes.ts
- Détails :
- Mock updown.io while e2e tests
- Use wildcard for api inclusion mocks
- Remove double slash in updown.io requests :
=> tests: mock updown.io while e2e tests

models/espace-agent/dirigeants-protected.ts, models/espace-agent/mergeDirigeants.test.ts, models/espace-agent/utils.ts, next-env.d.ts
- Correction d'un bug. 
- Détails :
- Les dates de naissance complètes ne s'affichent pas pour les agents connectés.
- Cela est du à une inversion des données du RCS et du RNE en entrée de mergeDirigeants : nous utilisons maintenant des variables nommées.
- Suppression du booléen inutilisé rcsNotRelevant
=> fix(dirigeants): fix birth date from inpi/ig

app/(header-default)/documents/[slug]/_components/actes/rne.tsx
- Détails :
- Some keys were not unique
Before :
After :
=> fix(actes): keys not unique

components/conventions-collectives-section/index.tsx
- Détails :
- Suppression du lien vers cdtn si idcc inconnu
- Ajout d'un paramètre d'url pour tracer l'origine des requêtes
Closes #1255 
Avant : 
Après :
=> feat(cdtn): no link when cdtn inconnue

clients/_test/clientAllEtablissementsInsee/index.test.ts, clients/_test/clientAnnuaireServicePublicByName/index.test.ts, clients/_test/clientAnnuaireServicePublicBySiret/index.test.ts, clients/_test/clientApiDataGouvEss/index.test.ts, clients/_test/clientAssociation/index.test.ts, clients/_test/clientBanGeoLoc/index.test.ts, clients/_test/clientBilansFinanciers/index.test.ts, clients/_test/clientBodacc/index.test.ts, clients/_test/clientCommunesByName/index.test.ts, clients/_test/clientDCA/index.test.ts, clients/_test/clientDepartementsByName/index.test.ts, clients/_test/clientEducationNationale/index.test.ts, clients/_test/clientEgapro/index.test.ts, clients/_test/clientEgaproRepresentationEquilibre/index.test.ts, clients/_test/clientEntrepreneurSpectacles/index.test.ts, clients/_test/clientEpcisByName/index.test.ts, clients/_test/clientJOAFE/index.test.ts, clients/_test/clientOrganismeFormation/index.test.ts, clients/_test/clientRGE/index.test.ts, clients/_test/clientRNEImmatriculation/index.test.ts, clients/_test/clientRegionsByName/index.test.ts, clients/_test/clientSearchRechercheEntreprise/searchFilter.test.ts, clients/_test/clientSearchRechercheEntreprise/simpleSearch.test.ts, clients/_test/clientTVA/index.test.ts, clients/_test/clientUniteLegaleInsee/index.test.ts, clients/_test/expect-client-to-match-snapshot.ts
- Détails :
- Suppression d'un test de snapshot de l'api entreprise avec un filtre peu précis, qui provoque des faux positifs de régression
- Fix d'une typo de nom de variable : snaphotFile -> snapshotFile
=> fix(snapshot test): reduce false positive and fix typo

app/(header-default)/entreprise/[slug]/_components/effectif-cell.tsx
- Détails :
- Quand il y avait un 404 pour la donnée protégée, rien ne s'affichait
Loader :
404 : 
Erreur : 
Good :
=> fix: effectif cell when 404

app/(header-default)/donnees-financieres/[slug]/page.tsx
Avoid unnecessary rendering when no right.
=> fix: check right before rendering bilans section

app/(header-default)/entreprise/[slug]/_components/effectif-cell.tsx
- Détails :
- Formattage de "Effectif annuel" en locale française
Avant :
Après :
=> fix: format number effectifs

.github/workflows/external-api-test.yml
Deuxième tentative pour signer les commits faits par le bot.
Documentation de `peter-evans/create-pull-request@v7` : "In this example the token input is not supplied, so the action will use the repository's default GITHUB_TOKEN. This will sign commits as github-actions[bot]."
=> fix(external-api-test): sign commits 2

clients/api-entreprise/association/index.ts, clients/api-entreprise/beneficiaires/index.ts, clients/api-entreprise/bilans/index.ts, clients/api-entreprise/certificats/qualibat.ts, clients/api-entreprise/certificats/qualifelec.ts, clients/api-entreprise/chiffres-affaires/index.ts, clients/api-entreprise/client.ts, clients/api-entreprise/conformite/fiscale.ts, clients/api-entreprise/conformite/msa.ts, clients/api-entreprise/conformite/vigilance.ts, clients/api-entreprise/effectifs/annuels.ts, clients/api-entreprise/mandataires-rcs/index.ts, clients/api-entreprise/opqibi/index.ts, clients/api-entreprise/travaux-publics/index.ts
- Refacto
- Détails :
- Le client api entreprise récupère une route plutôt qu'une URL
- L'URL est construite dans le client à partir de process.env.API_ENTREPRISE_URL
=> refacto(api entreprise client): use url env var in the client

.github/workflows/external-api-test.yml, .github/workflows/pre-merge.yml
Grâce au serveur de mocks pour les tests end to end, on a vraiment plus besoin de secrets pour les faire 😎
=> fix: remove secrets for e2e tests and external api tests

clients/api-entreprise/client.ts
- Détails :
- Le `sensitiveRequestLogger` a besoin d'une URL complète pour fonctionner.
- La refacto du client api entreprise a introduit ce bug en formant l'URL complète après le logger
=> fix: sensitive request logger get full url

app/api/data-fetching/[...slug]/route.ts, app/api/data-fetching/utils.ts, utils/session/with-session.ts
- Détails :
- Utilisation de withSession pour les routes api data
- `withIgnoreBot` avait un double rôle : ajout de la session et détection des bots
- Ces deux rôles sont maintenant occupés par deux wrappers différents : `withSession` and `withIgnoreBot`
#1552
=> feat: use withSession for data api routes

app/api/data-fetching/[...slug]/route.ts, models/association/index.ts, models/eori-validation.ts, models/espace-agent/dirigeants-protected.ts, models/rne/dirigeants.tsx, models/rne/observations.ts, models/tva/verify.ts, models/user/agent-scopes/parse.test.ts, models/user/agent-scopes/parse.ts
- ignore false scope validation alerts
- revert bot protection logic as redundant. See https://github.com/annuaire-entreprises-data-gouv-fr/site/blob/4ce830b92265f8fa508d6b82866041a5d0f364d8/app/api/data-fetching/utils.ts#L37
=> Fixes to scope and bot 

app/api/auth/agent-connect/callback/route.ts, models/authentication/agent/index.ts
Following yesterday deployment of siretisation by ProConnect, PC may return inconsistent siret format
This triggers a `NotASiretError` and fails connection (probably explains the MCAS case)
=> feat: remove whitespace in siret from ProConnect

cypress/e2e/fonctionnalites/static-pages.cy.js
- Détails :
- Remove e2e tests to external links as they fail randomly
- Add dedicated worflow for external links
Closes #1639
=> fix: end-to-end tests for footer links

components/table/copy-paste.module.css, components/table/copy-paste.tsx, components/title-section/etablissement/index.tsx, components/title-section/index.tsx
- Détails :
- Copier coller pour le siren en haut de la page
- En copiant manuellement, on obtenait en plus des espaces
=> feat: add copy paste for siren

app/(header-compte)/admin/page.tsx, components/conventions-collectives-section/index.tsx, components/etablissement-section/index.tsx
- Détails :
- Ajout de "key" dans des tableaux
- Une nouvelle fonctionnalité de Nextjs permet de les voir facilement :
=> fix: add missing keys for list items in components

.vscode/launch.json, models/authentication/agent/agent-connected/index.test.ts, package.json
- Zones impactées : `models/authentication/agent/agent-connected/index.test.ts`
- Détails :
- Tests unitaires pour la classe AgentConnected
- Debug dans VS Code
=> feat: add unit test for AgentConnected and debugging support

app/api/auth/agent-connect/callback/route.ts
As I modified userInfo.siret before the log, the log became useles... 🥲
=> fix: log justice does not work if you shadow replace siret before

.vscode/settings.json, models/user/agent.ts
This domain is used by all external employees of the MTE.
=> feat: exclude @i-carre.net emails from l'espace agent

components/title-section/tabs/index.tsx
My bad I introduced a regression here https://github.com/annuaire-entreprises-data-gouv-fr/site/commit/74a3baed6ff5c6fb7078bd5cb691ae75127e822b
Interesting we have e2e tests on pages themselves but not on tabs @rmonnier9
=> fix: idcc broken link

components/advanced-search/filter-structure.tsx, components/badges-section/labels-and-certificates/index.tsx, models/search/search-filter-params.ts
- Détails :
- Masquage du filtre société à mission jusqu'à ce qu'il soit de nouveau rendu opérationnel par l'INSEE
- Filtre et section "Achats Responsables" sont placés en fin de liste (nouvelle fonctionnalité)
Closes #1740
=> feat: hide temporary "Société à mission" filter

clients/external-tooling/grist.ts
depends on https://github.com/annuaire-entreprises-data-gouv-fr/infrastructure/pull/427
closes https://github.com/annuaire-entreprises-data-gouv-fr/site/issues/1689
@rmonnier9 I'm leaving the PR testing in your hands. The tables might be updated before you're back, so please double-check that they are identical before merging.
For reference:
* Old document: https://grist.numerique.gouv.fr/o/docs/hp8PLhMGY9sN/Annuaire-des-Entreprises
* New document: https://grist.numerique.gouv.fr/o/datagouv/uE2WGSjyBbSf/Site
The tableId are the same since I didn't change the table names.
I've also updated the API token in Ansible to use mine.
@XavierJp fyi
=> [Grist]chore: udpate grist docId

app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/alim-confiance/section.tsx, app/(header-default)/labels-certificats/[slug]/page.tsx, clients/recherche-entreprise/index.ts, clients/recherche-entreprise/interface.ts, components/badges-section/labels-and-certificates/index.tsx, models/core/types.ts
- Détails :
- Utilisation du champ est_alim_confiance
Question : Peut-être devrions-nous préciser la notion de labels et certificats ?
Alim'Confiance n'est ni l'un ni l'autre, juste un dispositif qui met en open data les résultats de contrôle sanitaire
=> fix: alim confiance

app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/alim-confiance/section.tsx, clients/api-data-gouv/alim-confiance/index.ts, clients/api-data-gouv/alim-confiance/interface.ts, clients/recherche-entreprise/index.ts, components/search-results/results-pagination/index.tsx, components/search-results/results-pagination/local-pagination.tsx, hooks/fetch/alim-confiance.ts
- Détails :
- Ajout d'une pagination pour alim'confiance
- Création d'un composant de pagination avec state local
Note UX : la pagination est en haut pour éviter les sauts lorsque l'on pagine (si la hauteur de la table est différente)
(cette PR contient les changements en double de l'autre PR Alim'Confiance, il vaut mieux d'abord merge https://github.com/annuaire-entreprises-data-gouv-fr/site/pull/1758)
=> feat: pagination alim confiance

data/administrations/mef.yml
- Détails :
- Correction du lien vers data gouv pour entreprise du patrimoine vivant
Closes #1775
=> fix: link entreprise patrimoine vivant data gouv

components/search-results/map/index.tsx
- Détails :
- Redirection de la recherche vers le format liste quand il n'y a pas de résultat
- Par défaut, toute recherche est donc sous format liste avec ensuite possibilité de l'afficher sous format carte
1. On ne montre plus une carte vide
2. Cela résout le fait que le toggle map/list n'est plus accessible quand il n'y a pas de résultat
@renardpal 
Problème - Carte vide et pas de toggle accessible
Closes #1783
=> feat: redirect search from map to list when no results

models/authentication/agent/agent-connected/index.test.ts, models/authentication/agent/agent-connected/index.tsx
- Détails :
- Some email seems to have consultant suffix
TODO
A vérifier, mais il semblerait que la DGFIP a des prestataires avec ce suffixe ?
@MKCG
=> feat: consultant email are prestataire

app/(header-default)/entreprise/[slug]/page.tsx, cypress/e2e/fonctionnalites/unite-legale-pagination.cy.js, cypress/e2e/recherche/research-redirections.cy.js
- Détails :
- Redirect when slug is a siren and a full path is available (not non diffusible)
Closes #1824
=> feat: add permanent redirect for entreprise slug when it is a siren

app/(header-compte)/compte/habilitation/[demandeId]/_components/validate-group-form.tsx, app/(header-compte)/compte/habilitation/[demandeId]/succes/page.tsx, components/espace-agent-components/helpers/form-validation.ts
closes #1943 
- error in workflow still displaying success page
- typo in `/compte/accueil` link
- form validation was broken
- email validation lacked good feedback
- missing `mes-groupes` link
=> fix: datapass implementation glitches

components/espace-agent-components/group-management/group-item.tsx
- Détails :
- Un admin peut se passer utilisateur si il y a un autre admin
Closes #1938
=> fix: admin can auto downgrade their role

components/footer/index.tsx
- Détails :
- Amélioration du wording sur le footer pour l'export Sirene
=> fix: improve wording footer export sirene

components/map/map-etablissement.tsx
- Zones impactées : Etablissement - Map.
- Détails :
- Suppression des coordonnées du message d'erreur lorsqu'elles sont invalides
related to #1942
=> fix(map): hides coordinates for invalid map
