annuaire-entreprises-data-gouv-fr/site

- components/introuvable/immatriculation.tsx
- pages/faq.tsx
> Cquest tribuanux

- clients/matomo/index.ts
- pages/api/form/index.ts
- pages/formulaire/index.tsx
> fix(stats): run NPS out of 10

- clients/matomo/index.ts
- clients/sirene-insee/siret.ts
- components/etablissement-liste-section/index.tsx
- components/title-etablissement-section/index.tsx
- pages/api/form/index.ts
- pages/carte/[slug].tsx
- pages/formulaire/index.tsx
> Sync test with main 

- README.md
PR non finalisée, dans l'attente des liens définitifs et des repos associés.
> Add repositories descriptions

- clients/routes.ts
Nouvelle route pour l'API de search (techno postgrest). 
Un changement d'infra nécessite le changement d'url.
> Update route search with new url

- clients/routes.ts
- clients/sirene-ouverte/recherche.ts
- Amélioration technique : passage sur elastic search en lieu et place de la recherche postgrest
> feature: switch to elastic and use eta administratif uniteLegale

- clients/exceptions.ts
- clients/rncs/site/IMR-parser.ts
- models/annonces.ts
- models/association.ts
- models/convention-collective.ts
- models/geo-loc.ts
- models/immatriculation/joafe.ts
- models/immatriculation/rncs.ts
- models/immatriculation/rnm.ts
- pages/_error.tsx
- utils/redirects/index.ts
> fix: better error handling and fix inpi parser error

- clients/matomo/index.ts
- pages/api/feedback/nps.ts
- pages/formulaire/index.tsx
> fix: add a uuid to avoid duplicate feedback submission

- components/banner/entreprise-data.tsx
- layouts/page.tsx
> temp: add a banner for entreprise.data

- cypress/integration/advanced-research.js
- next.config.js
- pages/_error.tsx
- sentry.client.config.js
- sentry.server.config.js
- utils/sentry/index.ts
> feature: use sentry/nextjs for transaction monitoring

- cypress/integration/advanced-research.js
- utils/network/0auth.ts
- utils/network/error-interceptor.ts
- utils/network/format-log.ts
- utils/network/index.ts
- utils/network/log-interceptor.ts
> feature: add time in std logs

- clients/routes.ts
- components/header/header-search.tsx
- components/matomo-event/search-click.tsx
- components/matomo-event/search-redirected.tsx
- models/search-filter-params.ts
- pages/entreprise/[slug].tsx
- pages/etablissement/[slug].tsx
- pages/rechercher/carte.tsx
- pages/rechercher/index.tsx
- utils/network/log-interceptor.ts
- utils/redirects/routers.ts
> fix: add matomo event in all searchs events

- components/immatriculations/rncs.tsx
> fix: add warning and hide pdf

- clients/exceptions.ts
- clients/ping-api-clients.ts
- pages/api/ping/[slug].ts
- utils/network/error-interceptor.ts
> fix: 508 error code in uptime robots

- clients/sirene-insee/siret.ts
- utils/helpers/formatting.test.ts
- utils/helpers/formatting.ts
@HAEKADI je me suis aligné sur ce qui est dans l'avis de situation insee, a savoir, ils ignorent le code pays
> feature: intl adress

- components/useful-shortcuts/index.tsx
> fix: useful shortcuts

- clients/sirene-insee/siren.ts
- clients/sirene-insee/siret.ts
- clients/sirene-ouverte/siren.ts
- components/dirigeants-section/summary.tsx
- components/etablissement-description/index.tsx
- components/etablissement-liste-section/index.tsx
- components/immatriculations/insee.tsx
- components/immatriculations/rnm.tsx
- components/results-list/index.tsx
- components/unite-legale-description/index.tsx
- components/useful-shortcuts/index.tsx
- models/convention-collective.ts
- models/etat-administratif.ts
- models/index.ts
- models/unite-legale.ts
> Split etablissements list

- clients/base-adresse/index.tsx
- components/dirigeants-section/rncs-dirigeants.tsx
- components/useful-shortcuts/index.tsx
- frontend/js/sentry.js
- models/etablissement.ts
- package-lock.json
- package.json
- pages/api/verify-tva/[slug].tsx
- pages/carte/[slug].tsx
- utils/sentry/apm.ts
- utils/sentry/index.ts
- utils/server-side-props-helper/post-server-side-props.ts
Add backend APM
Remove some unused packages
Group frontend routes in APM
> Sentry apm

- models/etablissement.ts
- models/unite-legale.ts
During sirene maintenance we systematically fallback on sirene ouverte
> Insee: fallback on sirene ouverte

- models/etablissement.ts
- models/unite-legale.ts
Reverts etalab/annuaire-entreprises-site#175
> Revert "Insee: fallback on sirene ouverte"

- components/title-section/index.tsx
Reverts etalab/annuaire-entreprises-site#179
> Revert "Warning: avis de situation is down"

- components-ui/social-media/index.tsx
- components/title-section/index.tsx
- pages/_document.tsx
- pages/justificatif-immatriculation-pdf/[slug].tsx
Update subject body of mail share option
> 204 share links

- models/unite-legale.ts
Call to API Search trigger rate limiting in /entreprise
This fix temporarly disable the call, only for bot
> Fix rate limiting search api

- functions/compute-stats.js
- pages/_error.tsx
- pages/rechercher/index.tsx
- seo-scripts/download-data.ts
- seo-scripts/index.ts
- seo-scripts/memory.ts
- seo-scripts/page-tree-builder.ts
- seo-scripts/read-line.ts
- seo-scripts/write-sitemap.ts
- utils/network/index.ts
- utils/network/log-interceptor.ts
- utils/sentry/index.ts
- utils/server-side-props-helper/error-handler.ts
> Refacto : remove every console.log

- .gitignore
- clients/open-data-soft/journal-officiel-associations.ts
- clients/routes.ts
- components/annonces-section/annonces-association.tsx
- components/annonces-section/comptes-association.tsx
- data/changelog.yml
- models/annonces.ts
- models/association.ts
- models/immatriculation/joafe.ts
- pages/annonces/[slug].tsx
- utils/helpers/formatting.ts
Display Organization accounting in **annonce** page 👇
> feat: display organization accounting in **annonce** page

- clients/monitoring/index.ts
cf https://github.com/axios/axios/issues/5346
closes #234
> fix: axios latest breaking change

- components/search-filters/index.tsx
- cypress/e2e/advanced-research.cy.js
- models/search-filter-params.ts
> feat: filtre etat administratif

- components/meta/index.tsx
- pages/index.tsx
- seo-script/page-tree-render/html-helpers.ts
> feat: title and description SEO

- components-ui/logo/home-h1.tsx
- components-ui/logo/index.tsx
- pages/index.tsx
Use html instead of SVG for home logo
closes #284
> feat: use <h1> for home logo

- clients/sirene-insee/siret.ts
- clients/sirene-ouverte/siret.ts
- components/etablissement-liste-section/index.tsx
- components/etablissement-section/index.tsx
- components/title-section/index.tsx
- components/unite-legale-section/index.tsx
- cypress/e2e/research.cy.js
- models/complements.ts
- models/index.ts
- models/unite-legale.ts
- pages/entreprise/[slug].tsx
- seo-script/page-tree-render/html-helpers.ts
- seo-script/page-tree-render/index.ts
- utils/helpers/get-company-page-title.ts
- utils/labels/index.ts
closes #247 
closes #249 
closes #250 
closes #283
> feat: revamp seo pages label, title and description

- README.md
- next.config.js
- package-lock.json
- package.json
> chore: adding next bundle analizer

- components/labels-and-certificates/entrepreneur-spectacles/index.tsx
- data/faq/entrepreneur-spectacles-vivants.yml
> fix: date validite and faq

- components-ui/information-tooltip/index.tsx
- components/error-explanations/index.tsx
- components/section/index.tsx
- package-lock.json
> fix: responsive

- clients/ping-api-clients.ts
- components/front-state-machine/index.tsx
- frontend/src/front-state-machine.js
- frontend/src/inpi-pdf-download.js
- models/association.ts
- models/geo-loc.ts
- models/immatriculation/rne.ts
- pages/justificatif-immatriculation-pdf/[slug].tsx
> fix: clean inpi pdf sentry messages

- clients/api-proxy/association/index.ts
- clients/open-data-soft/journal-officiel-associations.ts
- components-ui/alerts/immatriculation-not-found-alert.tsx
- components/immatriculations/end-of-life-warning.tsx
- components/immatriculations/index.tsx
- components/immatriculations/rncs.tsx
- components/immatriculations/rnm.tsx
- bug in Association Justification & annonces
- banner in justificatif
> fix: association justificatif

- models/unite-legale.ts
Reverts etalab/annuaire-entreprises-site#364
> Revert "fix: insee unresponsive"

- data/faq/adresse-personnelle.yml
- data/faq/association-introuvable.yml
- data/faq/entreprise-introuvable.yml
- data/faq/entreprise-non-diffusible.yml
- data/faq/rendre-mon-entreprise-non-diffusible.yml
- data/faq/supprimer-donnees-personnelles-entreprise.yml
- pages/vie-privee.tsx
Update de la page vie-privee pour prendre en compte la nouvelle procédure
Ajout de nouvelles page FAQ suite au travail de @Anais-Tailhade @karen et @jo
closes #374
> feat: update page vie-privee

- components-ui/alerts/immatriculation-not-found-alert.tsx
- components-ui/alerts/non-diffusible.tsx
- components/collectivite-territoriale-section/index.tsx
- components/title-section/index.tsx
- frontend/src/inpi-pdf-download.js
- models/constants.ts
- pages/justificatif-immatriculation-pdf/[slug].tsx
- Explain procedure to change diffusion status when partially diff
- Add contextual tooltiped explanation for Insee / COG in colter section
- Add many more contextual explanation to PDF download page to help user cope with failures and unexpected 404
closes #417
> Update Warnings, info and contextual help

- clients/egapro/index.ts
- components/advanced-search/filter-structure.tsx
- components/labels-and-certificates-badges-section/index.tsx
- components/labels-and-certificates/egapro/index.tsx
- data/changelog.yml
- data/faq/egapro-egalite-professionnelle-femme-homme.yml
- models/egapro.ts
- models/search-filter-params.ts
Improve egapro explanation
Handle empty score
Bring more contextual explanations and update FAQ
> feat: update egapro with egapro team comments

- clients/egapro/index.ts
- components-ui/alerts/immatriculation-not-found-alert.tsx
- components-ui/is-active-tag/index.tsx
- components-ui/tag/index.tsx
- components/immatriculations/insee.tsx
- components/immatriculations/rne.tsx
- components/labels-and-certificates/egapro/index.tsx
- cypress/e2e/unite-legale-pagination.cy.js
- data/faq/fiche-immatriculation-introuvable.yml
- models/certifications/egapro.ts
- models/certifications/index.ts
- models/etat-administratif.ts
- pages/justificatif-immatriculation-pdf/[slug].tsx
> Content & fixes

- models/unite-legale.ts
Reverts etalab/annuaire-entreprises-site#439
> Revert "[TMP] force callback on recherche entreprises for 404"

- clients/api-entreprise/conformite/fiscale.ts
- clients/api-entreprise/conformite/msa.ts
- clients/api-entreprise/conformite/vigilance.ts
- clients/routes.ts
- components/donnees-restreintes-section/[slug].tsx
- components/section/protected-section.tsx
- components/title-section/index.tsx
- models/constants.ts
- models/espace-agent/donnees-restreintes-entreprise.ts
- pages/entreprise/[slug].tsx
- pages/espace-agent/subventions-association/[slug].tsx
- hide subvention association
- remove tab logic for agents and prefer inlined protected sections
- add three new API Entreprise clients (vigilance, fiscale, msa)
closes #400
> feat: conformite in page entreprise

- components/immatriculations/rne.tsx
@yoanficadiere preneur de ton regard
@Anais-Tailhade cela peut t'intéresser. Ce changement crée un comportement spécial dans la section RNE quand elle en fonctionne pas. Plutot que de seulement dir ca marche pas, elle propose deux liens : 
- un vers le PDF qui lui peut encore fonctionner
- un lein vers le site de l'Inpi
> feat: add a dedicated section when RNE is not working

- .github/workflows/pre-merge.yml
- components/advanced-search/search-filters.tsx
- components/footer/index.tsx
- data/changelog.yml
- pages/budget.tsx
- pages/comment-ca-marche.tsx
- pages/equipe.tsx
> feat: adding our team page

- models/etablissement.ts
- models/unite-legale.ts
> feat: systematically use rehcerhce entreprise

- data/faq/données financières.md
Proposition de page FAQ pour les données financières 
Les indicateurs financiers (EBE, Marge brut etc...) pourraient également être explicités dans les bulles des pages financières mais je ne sais pas comment le proposer !
> Create données financières.md

- clients/matomo/index.ts
- functions/compute-stats.js
- next-env.d.ts
- pages/formulaire/nps.tsx
- utils/network/index.ts
> fix: nps result

- .github/workflows/pre-merge.yml
- .github/workflows/recipe-staging.yml
- components/search-results/advanced-search-tutorial.tsx
- cypress.config.ts
- package-lock.json
- package.json
- pages/administration/index.tsx
- pages/comment-ca-marche.tsx
- pages/donnees/sources.tsx
- seo-script/static-pages.ts
> feat: remove cypress plit and reactivate a11y

- clients/routes.ts
- components/avis-situation-link/index.tsx
- utils/helpers/formatting/labels.ts
- utils/helpers/formatting/metadata/conventions-collectives.ts
- fix avis situation
- handle edge cases of unknown idcc
> fix: 404 on avis situation link

- pages/api/stats/index.ts
- utils/helpers/formatting/labels.ts
Will be use to compile all operateur product's stats.
> feat: create a dedicated stats route

- clients/auth/mon-compte-pro/strategy.ts
- pages/api/auth/mon-compte-pro/callback.ts
Migration from `organizations` scope to `organization`
> feat: migration from organizations to organization in MCP

- clients/recherche-entreprise/index.ts
See https://github.com/etalab/annuaire-entreprises-search-api/pull/281
> feat: add include_admin fields

- clients/recherche-entreprise/index.ts
See https://github.com/etalab/annuaire-entreprises-search-api/pull/281
> feat: clean params following API #281

- .github/workflows/recipe-staging.yml
> chore: test regression for recipe staging

- clients/recherche-entreprise/index.ts
- clients/sirene-insee/siren.ts
- clients/sirene-insee/siret.ts
- utils/helpers/insee-variables/index.ts
- utils/helpers/insee-variables/insee-variables.test.ts
- fix bug
- add tests <3
@HAEKADI @skelz0r do you think we should do the same for the API ? 
I would rather document it in the swagger
> Fix 1900-01-01 creation dates for etablissement

- frontend/src/helpers-feedbacks.js
- pages/_document.tsx
- temporarly deactivate NPS banner
- implement tally integration
closes #624
> Direct Tally integration

- components-ui/alerts/association-adress.tsx
- components/api-monitoring/index.tsx
- components/association-section/index.tsx
- components/title-section/tabs.tsx
- data/administrations/djepva.yml
- data/administrations/mi.yml
- models/administrations/index.ts
- models/association.ts
- models/donnees-financieres/index.ts
- models/index.ts
- Add a new administration : DJEVPA
- Modify type of association response accordingly
- Change wording for accessing link to api doc
fix #630
> fix: add a specific message in section association when rna api is KO

- clients/sirene-insee/siren.ts
- components-ui/alerts/association-adress.tsx
- components/finances/societe/index.tsx
- components/immatriculations/rne.tsx
- components/map/map-etablissement.tsx
- models/geo-loc.ts
- models/statut-diffusion.ts
- models/unite-legale.ts
- pages/carte/[slug].tsx
- update warnings
- update `non-diffusible` logic : 
- remove `codePostal` as it is not diffusible
- remove coordinate as they are not diffusible
- dont call BAN when unnecessary
> feat: update warnings content

- components/layouts/layout-default.tsx
- components/layouts/layout-search.tsx
- components/modal/we-need-you.tsx
- frontend/src/helpers-feedbacks.js
> feat: create a lateral pop in for tally

- clients/api-proxy/association/index.ts
Seems like `comptes` went missing overnight. Really need to contact DJEPVA urgently
> fix: comptes missing in API RNA

- .github/workflows/deploy.yml
Github is in UTC -> Paris time - 2h
> feat: change auto deploy date

- clients/routes.ts
> feat: fallback TVA on staging

- frontend/src/fetch-tva.js
- utils/network/backend/redis/promise-timeout.ts
- utils/network/backend/redis/redis-storage.ts
- Add TVA context when front call fails
- Differentiate between timeout & other error in redis
> Improve sentry log for investigating on errors

- clients/_test/clientTVA/index.test.ts
- clients/api-vies/index.ts
- clients/exceptions.ts
- clients/ping-api-clients.ts
- clients/routes.ts
- models/tva/index.ts
- pages/donnees/api.tsx
- utils/network/index.ts
- utils/network/utils/http-error-handler.ts
cf title and https://github.com/etalab/annuaire-entreprises-api-proxy/pull/19/files
closes #707
> feat: migrate tva back on main server

- clients/matomo/index.ts
- utils/helpers/formatting/formatting.ts
Fix https://errors.data.gouv.fr/organizations/sentry/issues/129186
> fix: hydration error on pages with graph

- sentry.client.config.ts
- sentry.server.config.ts
See https://mattermost.incubateur.net/betagouv/pl/3p99jzmdutbdmqeyr4c7bcc34y
> fix: lower sentry sampling

- components/section/data-section-loader.tsx
> feat: use info rather than warning in data section loader

- sentry.server.config.ts
- Remove sensitive headers
- Add is_bot tag
> chore: improve sentry

- .github/workflows/external-api-test.yml
- .github/workflows/pre-merge.yml
- clients/_test/clientSearchRechercheEntreprise/_snapshots/CA-resultat-filter.json
- clients/_test/clientSearchRechercheEntreprise/_snapshots/collectivité-territoriale.json
- clients/_test/clientSearchRechercheEntreprise/_snapshots/search-198100125.json
- clients/_test/clientSearchRechercheEntreprise/_snapshots/search-200054781.json
- clients/_test/clientSearchRechercheEntreprise/_snapshots/search-300025764.json
- clients/_test/clientSearchRechercheEntreprise/_snapshots/search-338365059.json
- clients/_test/clientSearchRechercheEntreprise/_snapshots/search-351556394.json
- clients/_test/clientSearchRechercheEntreprise/_snapshots/search-528163777.json
- clients/_test/clientSearchRechercheEntreprise/_snapshots/search-839517323.json
- clients/_test/clientSearchRechercheEntreprise/_snapshots/search-842019051.json
- clients/_test/clientSearchRechercheEntreprise/_snapshots/search-843701079.json
- clients/_test/clientSearchRechercheEntreprise/_snapshots/search-880878145.json
- clients/_test/clientSearchRechercheEntreprise/_snapshots/search-88087814500015.json
- clients/_test/clientSearchRechercheEntreprise/_snapshots/search-883010316.json
- clients/_test/clientSearchRechercheEntreprise/_snapshots/search-908595879.json
- clients/_test/clientSearchRechercheEntreprise/_snapshots/search-xavier jouppe.json
- clients/_test/expect-client-to-match-snapshot.ts
- clients/_test/fetchRNEImmatriculation/index.test.ts
- [ci: use a separate build for E2E tests](https://github.com/etalab/annuaire-entreprises-site/commit/d7b3ecaea954e4d21c92bd92ade486fb82a33271)
- [ci: run external API on pull request](https://github.com/etalab/annuaire-entreprises-site/commit/e446a86599a3347c7c0ee0badf79b273d1184500) 
> We want to check error regularly, and to really look at them when they
trigger. Besides, some changes in the code can lead to regressions in
the client test, and we want to be aware of them as soon as possible.
> In return, we only trigger the test once per day, as it is not necessary
to spam the tchap channel when it's failing consecutively.
- [test: update snapshots following MAJ in recherche](https://github.com/etalab/annuaire-entreprises-site/commit/013130ae722f65c9691a8a3d4e941b3ee5a1156e)
- [test: …
> CI: various improvements

- clients/recherche-entreprise/index.ts
- clients/recherche-entreprise/interface.ts
- models/index.ts
- utils/helpers/checks.ts
Rely on API Recherche Entreprise to determibe if an `UniteLegale` is 
- an Association
- a ServicePublic
> refacto: isServicePublic and isAssociation use RechercheEntreprise

- README.md
> content: update readme protected-siren

- components/banner/browser-is-outdated.tsx
> fix: use innerHTML instead of just changing display

- components/etablissement-section/index.tsx
- components/table/simple.tsx
- components/tva-cell/index.tsx
- components/unite-legale-section/index.tsx
- cypress/e2e/faq.cy.js
- cypress/e2e/tva.cy.js
- data/definitions/tva-intracommunautaire.yml
- frontend/src/helpers-copy-paste.js
- update tva definition
- update different case and explanation
- update `TVACell` behaviour and 
- fix `CopyPaste` behaviour
closes #799
> feat: update TVA logic following meeting with DGFiP team

- clients/api-proxy/rne/documents.ts
- components/espace-agent-components/documents/bilans.tsx
- components/finances-section/societe/index.tsx
- models/immatriculation/index.ts
- pages/api/data-fetching/espace-agent/documents/[slug].tsx
- add tag for `Bilan consolidé`
- improve documentation
> feat: improve readibility for UL with many bilans

- pages/budget.tsx
> feat: update budget 2023

- frontend/src/fetch-tva.js
- only call VIES 25% of the time to avoid hitting the 40k / day limit that get our IP blocked
This is a temporary measure, waiting for a more durable solution
> feat: sample tva calls

- clients/recherche-entreprise/idcc-metadata.ts
- clients/recherche-entreprise/index.ts
- clients/recherche-entreprise/interface.ts
- components/administrations/index.tsx
- components/immatriculations/rne.tsx
- components/title-section/etablissement.tsx
- components/title-section/index.tsx
- components/title-section/tabs.tsx
- components/tva-cell/index.tsx
- data/administrations/inpi.yml
- models/conventions-collectives-list.ts
- pages/documents/[slug].tsx
- INPI name error
- format tva number
- hide link to justif for partial diffusible
- missing  whitespace following recent badge PR
- fix "document" tab not being display
> content: INPI correct name

- app/robots.ts
> feat: add labels & certifcats to robots.ts

- .github/workflows/deploy-cluster.yml
- introduce a new deploy to cluster action
- uses same naming convention for variables
> chore: create a dedicated gihtub action for cluster deployment

- scripts/seo/download-data.ts
See https://github.com/etalab/annuaire-entreprises-search-infra/pull/246/files
> chore: update sitemap url

- components-ui/button-agent-connect/index.tsx
- components/espace-agent-components/agent-wall/index.tsx
- components/immatriculations/rne.tsx
- components/search-results/results-list.tsx
- components/unite-legale-badge/index.tsx
- pages/connexion/agent-public.tsx
- multiple badges (suggestion from @johangirod)
- enhanced AgentConnect button affordance
- typo on `observation(s)`
> feat: typo, multi badge and better affordance

- components-ui/badge/index.tsx
> fix: text color in label in search page

- clients/matomo/index.ts
- components/stats/trafic.tsx
- pages/formulaire/nps.tsx
Voici à quoi cela ressemble : 
> ![image](https://github.com/etalab/annuaire-entreprises-site/assets/1775934/0a46ec9a-b7ca-4b2a-9e2b-0da0d83dc26c)
fix #851
> feat: add agent visit to stats page

- clients/recherche-entreprise/index.ts
- clients/recherche-entreprise/interface.ts
- clients/sirene-insee/siren.ts
- components-ui/alerts/no-siege-social.tsx
- components-ui/alerts/not-in-sirene-alert.tsx
- components/etablissement-liste-section/index.tsx
- components/title-section/index.tsx
- components/unite-legale-section/index.tsx
- models/core/types.ts
- models/core/unite-legale.ts
- utils/helpers/insee-variables/index.ts
> feat: handle no siret case.

- pages/_error.tsx
- utils/network/backend/error-interceptor.ts
- utils/network/backend/log-interceptor.ts
- utils/network/utils/format-log.ts
> chore: improve logs

- components/search-results/results-counter.tsx
- pages/personne/index.tsx
> spelling: add plural to result count

- components-ui/faq-link/style.module.css
- components-ui/information-tooltip/style.module.css
- components/save-favourite/index.tsx
- components/table/copy-paste.tsx
- components/table/simple.tsx
- components/table/styleSimple.module.css
- components/title-section/etablissement/index.tsx
- components/title-section/index.tsx
- components/title-section/tabs/index.tsx
- components/tva-cell/index.tsx
- sentry.client.config.ts
- sentry.server.config.ts
> TMP - various fix following server component merge

- app/layout.tsx
- components/matomo-event/init.tsx
- pages/_document.tsx
> feat: add matomo on /app

- components/header/header-advanced-search.tsx
- components/header/header-server.tsx
- components/header/index.tsx
- searchterm was lost in `header` during refacto !
> fix: add search term back

- app/(header-default)/entreprise/[slug]/page.tsx
- clients/routes.ts
- components/association-section/index.tsx
- data/administrations/dinum.yml
- hooks/fetch/association.ts
- models/association/index.ts
- pages/api/data-fetching/association/[slug].ts
- pages/api/data-fetching/rne/[slug].ts
> feat: ESS updown

- components/banner/browser-is-outdated.tsx
@johangirod not sure  I understand why the whole app is a children of `<IsOutdatedBanner />`
> fix: print broken on /entreprise

- app/(header-default)/error.tsx
- app/(header-home)/error.tsx
- app/(header-without-search)/error.tsx
- app/api/data-fetching/verify-tva/[slug]/route.ts
- components/error-explanations/index.tsx
- models/tva/verify.ts
- next.config.js
- sentry.client.config.ts
- utils/sentry/tracing.ts
- utils/server-side-helper/page/post-server-side-props.ts
> Various fixes

- clients/recherche-entreprise/index.ts
980506497
- 404 in Sirene since 3.11
- missing siret in siege in Recherche Entreprise -> breaks `/entreprise` page
> fix: missing siret breaks /entreprise

- clients/routes.ts
> chore: bump sirene version to 3.11

- app/(header-default)/faq/[slug]/page.tsx
- app/(header-default)/faq/modifier/[slug]/page.tsx
- app/(header-default)/faq/page.tsx
- app/(header-default)/faq/parcours/_components/parcours-questions.tsx
- components-ui/multi-choice/index.tsx
- components/faq-parcours/question.tsx
- components/search-results/advanced-search-tutorial/style.module.css
- components/search-results/results-list.tsx
- models/administrations/data-to-modify.ts
- models/administrations/index.ts
- utils/helpers/formatting/formatting.ts
- utils/helpers/formatting/labels.ts
- utils/server-side-helper/app/redirect-faq-not-found.ts
- fix a visual glitch when no NAF/APE
- fix a multi choice bug
- improve FAQ for Crisp and fix 404 in FAQ
> Spaghetti bowl

- clients/recherche-entreprise/index.ts
This will make annuaire-entreprise-site appear as a campaign in matomo Recherche API stats
> feat: add mtm campaign for tracking

- clients/matomo/index.ts
- clients/recherche-entreprise/index.ts
- components/stats/trafic.tsx
API stats 🎁
It s gonna be beautiful
> API stats 💪

- components/header/header-core/styles.module.css
> style: add breakpoint for header search bar

- clients/api-entreprise/client.ts
- utils/network/utils/sensitive-request-logger.ts
> [monitoring] await & fix sensitive request logging format

- clients/api-proxy/rne/documents.ts
- utils/network/utils/sensitive-request-logger.ts
- add sensitive logs on `/rne/documents`
- fix resource_type / resource_id
- add email domain to easily group by orga or do sanity checks
> feat: log agent on /document

- components-ui/floating-modal/index.tsx
- components-ui/floating-modal/style.module.css
- components/espace-agent-components/agent-wall/index.tsx
- components/espace-agent-components/agent-wall/style.module.css
- components/table/copy-paste.tsx
Pour reproduire :
https://annuaire-entreprises.data.gouv.fr/documents/423208180 en mobile et non connecté
> style: add responsive behaviour to FloatingModale

- utils/network/utils/sensitive-request-logger.ts
> [monitoring] resource_type: try to replace the siret and fallback to the siren

- app/(header-default)/entreprise/[slug]/page.tsx
- components-ui/alerts-with-explanations/association-adress.tsx
- components/association-section/index.tsx
- models/core/statut-diffusion.ts
> fix: association adress & non diffusion

- components-ui/faq-link/index.tsx
> fix: en savoir plus in tooltip

- components/map/map-etablissement.tsx
> fix: empty coords

- app/(header-default)/dirigeants/_component/sections/index.tsx
- app/(header-default)/vie-privee/page.tsx
- app/(header-without-search)/lp/agent-public/page.tsx
- clients/api-proxy/rne/index.ts
- components/espace-agent-components/agent-wall/index.tsx
- components/footer/index.tsx
- components/unite-legale-page-link/index.tsx
- middleware.ts
- package-lock.json
- package.json
- fix redirection log
- add cgu link
- update vie prive
- fix dirigeant page issue with useSession/getSession
- remove unecessary call to RNE
-
> content: remove 3rd party with no personnal data

- components-ui/icon/wrapper.tsx
- components-ui/information-tooltip/index.tsx
- components/espace-agent-components/documents/data-section/actes.tsx
- components/table/copy-paste.tsx
- models/exceptions.ts
- sentry.client.config.ts
- Hydration error
- Grouping error on sentry
- NotAllowedError
- ...
> Various sentry error fixes

- components/map/check-lat-lng.ts
- components/map/map-etablissement.tsx
- components/map/map-results.tsx
FIx maplibre crash when latitude or longitude are invalid.
> fix: only display marker when coords exist

- app/(header-default)/dirigeants/[slug]/page.tsx
- app/(header-default)/dirigeants/_component/sections/service-public-responsables.tsx
- app/(header-default)/dirigeants/_component/sections/service-public-subservices.tsx
- clients/open-data-soft/clients/annuaire-service-public/index.ts
- hooks/fetch/service-public-subservices.ts
- models/service-public/index.ts
- utils/network/frontend/index.ts
> Sub services in dirigeant page for service public

- app/(header-default)/dirigeants/[slug]/_component/sections/service-public-responsables.tsx
- app/(header-default)/dirigeants/[slug]/page.tsx
- app/(header-default)/entreprise/[slug]/page.tsx
- app/(header-default)/etablissement/[slug]/page.tsx
- app/api/data-fetching/espace-agent/carte-professionnelle-TP/[slug]/route.ts
- clients/open-data-soft/clients/annuaire-service-public/index.ts
- components/service-public-section/index.tsx
- hooks/fetch/service-public.ts
- models/service-public/index.ts
- fix bug FNTP (wrong scope)
- migrate SP to the front end (recently ODS seems pretty slow)
closes #1097
> chore: migrate service public to the client

- app/(header-default)/entreprise/[slug]/page.tsx
- app/api/data-fetching/espace-agent/_helper.ts
- app/api/data-fetching/espace-agent/carte-professionnelle-TP/[slug]/route.ts
- app/api/data-fetching/espace-agent/carte-professionnelle-travaux-public/[slug]/routes.ts
- app/api/data-fetching/espace-agent/conformite/[slug]/route.ts
- app/api/data-fetching/espace-agent/opqibi/[slug]/route.ts
- app/api/data-fetching/espace-agent/qualibat/[slug]/route.ts
- app/api/data-fetching/espace-agent/qualifelec/[slug]/route.ts
- clients/api-entreprise/carte-professionnelle-travaux-publics/index.ts
- clients/api-entreprise/client.ts
- clients/api-entreprise/conformite/fiscale.ts
- clients/api-entreprise/conformite/msa.ts
- clients/api-entreprise/conformite/vigilance.ts
- clients/api-entreprise/immatriculation-eori/index.ts
- clients/api-entreprise/mandataires-rcs/index.ts
- clients/api-entreprise/opqibi/index.ts
- clients/api-entreprise/qualibat/index.ts
- clients/api-entreprise/qualifelec/index.ts
- clients/api-proxy/rne/documents.ts
- components/etablissement-section/index.tsx
- models/espace-agent/carte-professionnelle-travaux-publics.ts
- models/espace-agent/certificats/opqibi.ts
- models/espace-agent/certificats/qualibat.ts
- models/espace-agent/certificats/qualifelec.ts
- models/espace-agent/conformite.ts
- models/espace-agent/immatriculation-eori.ts
- models/espace-agent/mandataires-rcs.ts
- models/espace-agent/utils.ts
- utils/network/utils/sensitive-request-caller-infos.ts
- utils/network/utils/sensitive-request-logger.ts
- no sensitive API can be called without an email
- no need to think about agentSiret these are automatically fetch from session before API Entreprise call
- add a resourceName for every API Entreprise `handleError`
> Improve API Entreprise safety

- models/core/index.ts
- models/core/unite-legale.ts
Systematically fallback on a call to sirene API when no siege
closes #1118
> 1118 insee siege

- app/(header-default)/dirigeants/[slug]/_component/sections/beneficiaires.tsx
- app/(header-default)/dirigeants/[slug]/_component/sections/summary.tsx
- app/(header-default)/documents/[slug]/page.tsx
- app/(header-default)/historique-des-modifications/_components/index.tsx
- data/changelog.yml
closes #1132
And add a warning for RBE access restriction + changelog
> fix: incorrect canonical in documents

- app/(header-default)/a-propos/comment-ca-marche/page.tsx
- app/(header-default)/historique-des-modifications/_components/index.tsx
- app/(header-default)/historique-des-modifications/page.tsx
- data/changelog.yml
- models/historique-modifications/index.ts
- pages/donnees/api-entreprises.tsx
> feat: add an API  category in changelog

- clients/recherche-entreprise/index.ts
- models/core/etablissements-list.ts
- models/core/unite-legale.ts
> fix: use real open etablissmeent count

- app/(header-without-search)/lp/agent-public/page.tsx
- components-ui/button-agent-connect/index.tsx
- components/espace-agent-components/agent-wall/index.tsx
- components/header/menu/espace-agent-link.tsx
- components/header/menu/index.tsx
- components/matomo-event/index.tsx
- pages/connexion/agent-public.tsx
- utils/matomo/index.ts
> feat: add conversion events

- app/(header-default)/labels-certificats/[slug]/page.tsx
- components/labels-and-certificates/organismes-de-formation/index.tsx
> refactor: quliopi typo and certif order

- clients/sirene-insee/siren.ts
> fix: remove denominationUsuelleUniteLegale from nomComplet

- app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/beneficiaires/agent-section.tsx
- style/globals.css
> Add modalité info in bénéficiaire table

- models/user/agent.ts
- pages/api/auth/agent-connect/callback.ts
- public/acces-refuse.html
- utils/integrations/grist.ts
- utils/network/utils/sensitive-request-caller-infos.ts
- create a table logs in grist
- for each successful conexion add a log
> feat: add connexion logs in grist

- app/(header-default)/justificatif-immatriculation-pdf/[slug]/page.tsx
> Texte sur téléchargement du justificatif d'immatriculation

- clients/sirene-insee/siren.ts
- utils/helpers/formatting/formatting.ts
closes #1217 
Bug introduced in 
https://github.com/annuaire-entreprises-data-gouv-fr/site/commit/1fb91c8e675173f6d63dcff3620f77c2641cca6e
> fix: formatName issue

- .vscode/launch.json
- Environnement de dev
- Zones impactées : `./.vscode/launch.json`.
- Détails :
- Mise à jour de la configuration du debugger
> feat: update vscode debugger configuration

- app/(header-default)/entreprise/[slug]/_components/summary-section.tsx
- clients/ping-api-clients.ts
- clients/recherche-entreprise/dirigeants.ts
- clients/recherche-entreprise/index.ts
- clients/recherche-entreprise/siren.ts
- clients/recherche-entreprise/siret.ts
- clients/routes.ts
- components/administrations/index.tsx
- components/eori-cell/index.tsx
- components/finances-section/association/index.tsx
- models/core/unite-legale.ts
- models/eori-validation.ts
- models/search/index.ts
Remove dead code : 
- console 
- old fallback in recherche api
> chore: remove useless fallback on recherche entreprise

- .env.dev
- middleware.ts
- Zones impactées : `middleware.ts`.
- Détails :
- Add an env variable for base url
- Only use it in the middleware
> feat: add env var for base url

- components/feedback-modal/feedback-form.tsx
- Zones impactées : `./components/feedback-modal/feedback-form.tsx`.
- Détails :
- add link to linkedin and tchap for agents
Closes #1247
> feat: add link to linkedin and tchap for agents

- app/(header-default)/dirigeants/[slug]/_component/sections/association/dirigeants.tsx
- app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/dirigeant-content.tsx
- app/(header-default)/donnees-financieres/[slug]/_components/bilans.tsx
- app/(header-default)/faq/parcours/_components/parcours-questions.tsx
- app/(header-default)/justificatif-immatriculation-pdf/[slug]/_components/pdf-failed.tsx
- components/finances-section/societe/index.tsx
- components/labels-and-certificates/rge/index.tsx
- components/map/map-etablissement.tsx
- components/map/map-results.tsx
- components/section/data-section/client.tsx
- components/table/full.tsx
- pages/erreur/administration/[slug].tsx
- utils/helpers/formatting/categories-entreprise.ts
- utils/static-pages/load-all.ts
- Zones impactées : `multiple`.
- Détails :
- Suppressions de @ts-ignore (quick wins seulement)
> chore: remove ts-ignore

- .github/workflows/deploy-cluster.yml
cf title
to merge when @MKCG have ended prod-01 migration
> chore: add back production-01

- app/api/auth/agent-connect/callback/route.ts
- app/api/auth/agent-connect/login/route.ts
- app/api/auth/agent-connect/logout-callback/route.ts
- app/api/auth/agent-connect/logout/route.ts
- app/api/auth/france-connect/callback/route.ts
- app/api/auth/france-connect/login/route.ts
- app/api/auth/france-connect/logout-callback/route.ts
- app/api/auth/france-connect/logout/route.ts
- components/header/changelog-notification.tsx
- components/section/data-section/client.tsx
- middleware.ts
- utils/server-side-helper/app/get-absolute-site-url.ts
- utils/server-side-helper/app/get-url.ts
- utils/server-side-helper/app/redirect-to.ts
- Correction d'un bug
- Zones impactées : `/api/auth`.
- Détails :
- change redirectTo to getURL
> Fix france connect

- components/faq-parcours/question.tsx
- models/user/helpers.ts
- Zones impactées : `./components/faq-parcours/question.tsx`.
- Détails :
- Lien tchap
- nom complet
- typo
> feat: add tchap link, provide fullname and typo

- app/(header-default)/annonces/[slug]/_components/bodacc.tsx
- clients/api-data-subvention/index.ts
- clients/api-entreprise/association/index.ts
- clients/api-entreprise/beneficiaires/index.ts
- clients/api-entreprise/carte-professionnelle-travaux-publics/index.ts
- clients/api-entreprise/conformite/fiscale.ts
- clients/api-entreprise/conformite/msa.ts
- clients/api-entreprise/conformite/vigilance.ts
- clients/api-entreprise/mandataires-rcs/index.ts
- clients/api-entreprise/opqibi/index.ts
- clients/api-entreprise/qualibat/index.ts
- clients/api-entreprise/qualifelec/index.ts
- clients/routes.ts
- Détails :
- Fix du lien
- Refacto every replace with functions
Closes #86
> fix: link to bodacc

- utils/integrations/grist.ts
- Détails :
- Add Sentry Grist
> feat: add sentry log for grist errors

- app/api/data-fetching/utils.ts
- Détails :
- Formattage du message de la même manière que le message antibot
> fix: error message when scraping

- .github/workflows/pre-merge.yml
- cypress/e2e/certifications.cy.js
- cypress/e2e/espace-agent.cy.js
- utils/session/index.ts
- Zones impactées : `espace-agent.cy.js`.
- Détails :
- Test espace agents
Closes #1123
> fix: espace agent test

- .github/workflows/deploy-cluster-full.yml
- .github/workflows/deploy-cluster-staging.yml
- components/faq-parcours/question.tsx
- data/faq/adresse-personnelle.yml
- data/faq/association-introuvable.yml
- data/faq/convention-collective.yml
- data/faq/egapro-egalite-professionnelle-femme-homme.yml
- data/faq/entrepreneur-spectacles-vivants.yml
- data/faq/entreprise-introuvable.yml
- data/faq/entreprise-non-diffusible.yml
- data/faq/extraire-liste-entreprises.yml
- data/faq/extrait-kbis.yml
- data/faq/fiche-immatriculation-introuvable.yml
- data/faq/fraudes-ecroqueries-annuaire-des-entreprises.yml
- data/faq/frequence-mise-a-jour-donnees.yml
- data/faq/justificatif-immatriculation-non-diffusible.yml
- data/faq/modifier-adresse.yml
- data/faq/pro-connect.yml
- data/faq/professionnels-bio.yml
- data/faq/qualiopi-organisme-formation.yml
- data/faq/reconnu-garant-environnement.yml
- data/faq/registre-des-beneficiaires-effectifs.yml
- data/faq/rendre-mon-entreprise-non-diffusible.yml
- data/faq/reutiliser-les-donnees.yml
- data/faq/supprimer-donnees-personnelles-entreprise.yml
- ajout d'un bandeau dans la page de contact
- deux nouvelles pages de FAQ 
- proconnect
- fraude
> content: faq pro connect and fraud

- pages/api/share/button/[slug].ts
- pages/erreur/introuvable/[slug].tsx
- Détails :
- Validate siret and siren
> fix: validate siren and siret

- components/load-bar/index.tsx
- components/title-section/tabs/index.tsx
- components/title-section/tabs/tab-link.tsx
This PR aims to be an open discussion about removing the `<Link />` component :
- rely a bit too much on next magic
- does not fix hydration issues
- creates bugs 
- pathFrom bug
- current cancelloadbar ug
- race condition in load bar
> refactor: remove links

- .github/workflows/pre-merge.yml
- app/api/auth/agent-connect/callback/route.ts
- app/api/auth/agent-connect/login/route.ts
- app/api/auth/agent-connect/logout/route.ts
- app/api/auth/france-connect/login/route.ts
- clients/authentication/france-connect/strategy.ts
- clients/authentication/pro-connect/strategy.ts
- cypress/e2e/espace-agent.cy.js
- models/user/agent.ts
- Détails :
- Pro connect related functions are renamed accordingly to increase clarity in the codebase
Note : 
Env variables and callback urls are not changed.
> chore: rename agent connect to pro connect

- app/(header-default)/personne/page.tsx
- data/changelog.yml
- package-lock.json
Also : 
- bump vuln
- update changelog data
> fix: personne page following next bump

- components/faq-parcours/question.tsx
- Détails :
- Ajustement de la hauteur du formulaire suite à l'ajout du champs SIRET
NB : l'ajout du champ a été fait directement sur Crisp : https://app.crisp.chat/website/064fca1b-bdd6-4a81-af56-9f38e40953ad/plugins/settings/b68ffdd2-ba6e-46a6-94bb-d0a9872ce09a/
Closes #1333
> fix: adjust height of the form

- app/(header-default)/dirigeants/[slug]/_component/sections/association/dirigeants.tsx
- app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/beneficiaires/ask-use-case.tsx
- app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/beneficiaires/index.tsx
> chore: fix typos

- components/footer/index.tsx
> chore: fix typo

- instrumentation.ts
- next.config.js
- package-lock.json
- package.json
- Détails :
- add missing instrumentation file
- fix sentry config that should now correctly sets source maps
Instrumentation file :
> chore: improve sentry config

- app/api/auth/agent-connect/agent-connect-types.ts
- app/api/auth/agent-connect/callback/route.ts
Improve context in `AgentConnectFailedException`
> fix: improve logging on AgentConnectionFailed exception

- .github/workflows/deploy-cluster-full.yml
- .github/workflows/deploy-cluster-staging.yml
- .github/workflows/external-api-test.yml
- .github/workflows/pre-merge.yml
> chore: update github actions

- next.config.js
Remove annoying warnings that can't be fixed.
> fix: remove build warning not fixable

- .github/workflows/deploy-cluster-full.yml
temporary workaround :
https://github.com/annuaire-entreprises-data-gouv-fr/site/actions/workflows/deploy-cluster-full.yml
> chore: temporarly disable staging deployment in CD

- next.config.js
- package-lock.json
- package.json
> fix: improve sentry config 2

- next.config.js
Debug header for all resources.
> feat: add header for deploy

- .github/workflows/deploy-cluster-full.yml
Reverts annuaire-entreprises-data-gouv-fr/site#1359
> Re-enable staging deployment in CD

- next.config.ts
- Amélioration technique et Correction d'un bug. 
Update to .ts
Fix next config from previous PR (add source for header)
> chore: next.config.ts

- app/(header-default)/dirigeants/[slug]/_component/sections/association/dirigeants.tsx
- app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/summary.tsx
- app/(header-default)/documents/[slug]/_components/actes/associations.tsx
- app/(header-default)/entreprise/[slug]/_components/inscriptions.tsx
- components/association-section/index.tsx
- components/espace-agent-components/agent-wall/association.tsx
- components/finances-section/association/index.tsx
- components/subventions-association-section/index.tsx
- data/faq/association-introuvable.yml
closes #1275 
- Improve open data explanations
- add a year filter to help with data analysis
Have a nice week end
> feat: feedback on open data

- utils/helpers/random-id.ts
- Détails :
- Lié à https://github.com/annuaire-entreprises-data-gouv-fr/site/security/code-scanning/2
> fix: use crypto for random bytes

- app/(header-minimal)/formulaire/nps/page.tsx
- clients/routes.ts
- components/banner/nps.tsx
- components/subventions-association-section/index.tsx
- data/administrations/djepva.yml
- Détails :
- Fix typos
- Fix total data sub
- Add link to data sub
> Fix typos and improve data sub

- components/banner/browser-is-outdated.tsx
- components/header/menu/index.tsx
- components/header/menu/styles.module.css
this is burning my eyes. Hope this will fix it
> style: css margin conflict in modal

- app/api/auth/agent-connect/agent-connect-types.ts
- app/api/auth/agent-connect/callback/route.ts
- models/user/agent.ts
- models/user/getSiretFromIdpTemporary.ts
- Zones impactées : `agent-connect/callback`.
- Détails :
- Ajout d'une table de correspondance idpid et siret
Closes #1377
> feat(agent-connect/callback): add mapping table idpid and siret

- app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/dirigeants-content-protected.tsx
- models/rne/types.ts
> fix: improve inpi / ig comparison

- models/user/agent.ts
https://errors.data.gouv.fr/organizations/sentry/issues/149120/?query=is%3Aunresolved+AgentConnectionFailedException&referrer=issue-stream&statsPeriod=14d
> fix: remove whitespaces from MCP siren

- app/(header-default)/a-propos/stats/page.tsx
- app/(header-default)/donnees/api/page.tsx
- Détails :
- Revert de la PR qui utilisait unstable cache
- Ajout de `export const dynamic = 'force-static';`
> fix: correctly implement isr

- app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/EtatCivilInfos.tsx
- app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/RolesInfos.tsx
- app/(header-default)/elus/_component/section/elus-section.tsx
- models/espace-agent/mergeDirigeants.test.ts
- models/espace-agent/utils.ts
- models/rne/types.ts
- Détails :
- Standardisation de l'affichage des prénoms (capitalisés, séparés par des virgules, sans accents) et des noms/dénomination,/nature juridique (sans accents, en majuscule)
- Affichage de tous les prénoms systématiquement (IG renvoie identiques les prénoms/prénom parfois)
- Lorsqu'un rôle est null, il ne s'affiche pas
> Fix inpi ig

- components/badges-section/labels-and-certificates/protected-certificats.tsx
Should fix the bug @HAEKADI mentionned this morning
Also much simpler to read
> reffactor: certificates badges

- README.md
- app/(header-default)/a-propos/comment-ca-marche/page.tsx
- app/(header-default)/a-propos/donnees-extrait-kbis/page.tsx
- app/(header-default)/donnees/api-entreprises/page.tsx
- data/administrations/ademe.yml
- data/administrations/agence-bio.yml
- data/administrations/dila.yml
- data/administrations/dinum.yml
- data/administrations/insee.yml
- data/administrations/marche-inclusion.yml
- models/core/unite-legale.ts
- utils/sentry/index.ts
> Update every apigouvlink & fix IG 400 for not luhn valid siren

- app/(header-default)/partager/page.tsx
- next.config.ts
A ne pas merger.
Paramétrage des en-têtes 'Content-Security-Policy' avec Next pour tester en local.
> Content-Security-Policy

- next.config.ts
A ne pas merger.
Paramétrage des en-têtes 'CORS' avec Next pour tester en local.
> Cross-origin resource sharing (CORS)

- next.config.ts
Add directives following staging tests.
> fix: add csp directives

- next.config.ts
> fix: add csp directives 2

- next.config.ts
> fix: add all open data soft

- app/(header-default)/elus/_component/section/elus-section.tsx
- clients/api-entreprise/mandataires-rcs/index.ts
- clients/api-proxy/rne/index.ts
- clients/recherche-entreprise/mapToDomain/index.ts
- models/espace-agent/mergeDirigeants.test.ts
- models/espace-agent/utils.ts
- models/rne/types.ts
- utils/helpers/formatting/formatting.test.ts
- utils/helpers/formatting/formatting.ts
- Détails :
- Le RNE renvoie un unique champ "prenom" avec tous les prenoms. Deux champs sont créés : prenom et prenoms.
Closes #1399
> fix: dirigeant comparison

- app/api/data-fetching/[...slug]/route.ts
- models/espace-agent/dirigeants-protected.ts
EI avec IG
http://localhost:3000/dirigeants/305179988
EI avec INPI
http://localhost:3000/dirigeants/823310099
Non EI
http://localhost:3000/dirigeants/552032534
> fix: ei dirigeant

- next.config.ts
> fix: missing data.inpi.fr

- next.config.ts
- utils/headers/content-security-policy.ts
- Correction d'un bug. 
- Détails :
- Ajout de directives CSP nécessaire pour la carte
- Refacto des CSP dans un fichier dédié
Les deux lignes ajoutées sont :
> fix: update csp for map dependencies

- components-ui/select/multi-select.tsx
- components-ui/select/type.tsx
> chore: improve multi-select type

- components-ui/select/multi-select.tsx
- components/banner/nps.tsx
- components/client-only/index.tsx
- components/map/map-results.tsx
- Détails :
- Création d'un composant ClientOnly destiné à éviter les erreurs d'hydratation
- Amélioration du typage de map
- Utilisation de ClientOnly sur le multi select et sur la bannière NPS
Avant : 
Après :
> fix: remove hydration errors

- app/(header-default)/administration/[slug]/page.tsx
- app/(header-default)/administration/page.tsx
- app/(header-default)/justificatif-immatriculation-pdf/[slug]/_components/inpi-pdf-downloader.tsx
- components/advanced-search/search-filters.tsx
- components/faq-parcours/question.tsx
- models/conventions-collectives/idcc-updates.ts
- utils/helpers/formatting/codes-effectifs.ts
- utils/helpers/formatting/formatting.ts
- utils/helpers/formatting/labels.ts
- utils/helpers/formatting/metadata/categories-juridiques.ts
- utils/helpers/formatting/metadata/codes-NAF-1993.ts
- utils/helpers/formatting/metadata/codes-NAF-rev-1.ts
- utils/helpers/formatting/metadata/codes-NAF-rev-2.ts
- utils/helpers/formatting/metadata/codes-NAP.ts
- utils/helpers/formatting/metadata/codes-section-NAF.ts
- utils/helpers/formatting/metadata/codes-voie.ts
- utils/helpers/formatting/metadata/departements.ts
- Détails :
- Add some keys
- Remove some ts-ignore
> chore: add keys and remove some ts-ignore

- app/api/share/button/[slug]/route.ts
- app/api/share/qr/[slug]/route.ts
> fix: remove verbose errors

- clients/stub-client-with-snaphots.ts
- components/map/map-etablissement.tsx
- components/markdown/parse-markdown.ts
- components/section/data-section/index.tsx
- models/administrations/index.ts
- models/core/types.ts
- models/landing-pages/index.ts
- models/search/search-filter-params.ts
- package-lock.json
- package.json
- utils/network/backend/index.ts
- utils/network/backend/log-interceptor.ts
> chore: remove ts-ignore 2

- app/(header-connexion)/connexion/echec-connexion/page.tsx
- app/(header-connexion)/error.tsx
- models/user/agent.ts
- add an isLuhnValid condition
Todo : alert DGE team to check if it works now
> fix: FI can return a siret that is invalid

- app/api/auth/agent-connect/callback/route.ts
- app/api/auth/agent-connect/logout-callback/route.ts
- components/banner/reconnect.tsx
- components/header/header-core/index.tsx
- utils/cookies/browser-cookies.ts
- utils/session/index.ts
- Détails :
- Les sessions durent 1 journée
- Ajout d'une bannière pour proposer une reconnexion suite à une deconnexion
> feat: 1 day session and reconnect banner

- clients/api-data-subvention/index.ts
- clients/stub-client-with-snaphots.ts
- components-ui/select/type.tsx
- components/subventions-association-section/index.tsx
- models/subventions/association/index.ts
- models/user/rights.ts
- models/user/scopes.ts
- utils/session/index.ts
- open data sub to everyone
- reset session for everyone
- add label filter in sub
> feat: status filter

- clients/rge/index.ts
- cypress/e2e/certifications.cy.js
- cypress/fixtures/example.json
- cypress/fixtures/rge.json
- cypress/mocks/handlers/rge.ts
- cypress/mocks/routes.ts
- Détails :
- Remove stub for rge
- Use msw to intercept request and use a fixture
> test: remove stub for rge

- clients/_test/clientSearchRechercheEntreprise/_snapshots/search-302474648.json
- clients/_test/clientSearchRechercheEntreprise/simpleSearch.test.ts
- cypress/e2e/certifications.cy.js
- cypress/fixtures/api-bio.json
- cypress/mocks/handlers/api-bio.ts
- cypress/mocks/routes.ts
- Détails :
- Ajout de test e2e pour api bio
> test: add bio e2e test

- clients/open-data-soft/clients/entrepreneur-spectacles/index.ts
- cypress/e2e/certifications.cy.js
- cypress/fixtures/entrepreneur-spectacles.json
- cypress/mocks/handlers/entrepreneur-spectacles.ts
- cypress/mocks/routes.ts
- Détails :
- Remove stub and add fixture for msw interception
> test: remove stub for entrepreneur spectacles

- clients/_test/clientApiDataGouvEss/_snapshots/ai-data-gouv-ess-800329849.json
- clients/_test/clientApiDataGouvEss/index.test.ts
- clients/api-data-gouv/ess/index.ts
- clients/api-data-gouv/ess/interface.ts
- cypress/fixtures/api-data-gouv-ess.json
- cypress/mocks/handlers/api-data-gouv-ess.ts
- cypress/mocks/routes.ts
- Détails :
- Ajout de snapshot pour test de regression sur api data gouv ess
- Mock pour test end-to-end pour api data gouv ess
> test(ess): add mock for e2e tests and snapshot for regression

- .github/workflows/deploy-cluster-full.yml
> chore: dont deploy on week ends

- components/banner/reconnect.tsx
- remove cookie onBeforeUnload event
- improve explanation
> feat: remove reconnect cookie on unload and update text

- clients/egapro/index.ts
- clients/egapro/representationEquilibre.ts
- clients/egapro/types.ts
- cypress/e2e/certifications.cy.js
- cypress/fixtures/egapro-representation.json
- cypress/fixtures/egapro.json
- cypress/mocks/handlers/egapro.ts
- cypress/mocks/routes.ts
- Détails :
- Remove stub for egapro
> tests: remove stub for egapro

- clients/_test/clientBanGeoLoc/index.test.ts
- clients/base-adresse-nationale/index.tsx
- clients/base-adresse-nationale/types.ts
- clients/routes.ts
- cypress/fixtures/base-adresse-nationale.json
- cypress/mocks/handlers/base-adresse-nationale.ts
- cypress/mocks/routes.ts
- models/association/index.ts
- models/geo-loc.ts
- Détails :
- Remove stub for base adresse nationale
> tests: remove stub for base adresse nationale

- clients/routes.ts
- clients/sirene-insee/siren.ts
- clients/sirene-insee/siret.ts
- cypress/mocks/routes.ts
- Détails :
- Use wildcards to intercept all requests to insee
> fix: remove stub insee 2

- app/(header-default)/a-propos/budget/page.tsx
- app/(header-default)/a-propos/equipe/page.tsx
- app/(header-default)/a-propos/stats/page.tsx
- app/(header-default)/donnees/api/page.tsx
- app/(header-default)/historique-des-modifications/page.tsx
- Détails :
- Suppression de no follow
Closes #1458
> fix: remove no follow

- clients/api-proxy/association/index.ts
- clients/api-proxy/greffe/index.ts
- clients/api-proxy/greffe/types.ts
- clients/api-proxy/rne/documents.ts
- clients/api-proxy/rne/index.ts
- clients/api-proxy/rne/types.ts
- clients/routes.ts
- cypress/e2e/dynamic-pages.cy.js
- cypress/mocks/handlers/association.ts
- cypress/mocks/handlers/ig.ts
- cypress/mocks/handlers/rne.ts
- cypress/mocks/routes.ts
- Détails :
- Remove stub for api-proxy
> chore: remove stub for api proxy

- components/banner/reconnect.tsx
- incorrect use of `useEffect` resulted in the banner never displaying
- currently the banner will only get displayed once
> fix: issue with useEffect clean

- components/faq-parcours/question.tsx
- utils/matomo/index.ts
add 3 type of events on parcours 
- modif
- contact
- faq question
> feat: matomo event on FAQ parcours

- clients/routes.ts
- cypress/mocks/routes.ts
- next-env.d.ts
> fix: wrong variable in msw routes

- clients/recherche-entreprise/index.ts
- clients/recherche-entreprise/mapToDomain/index.ts
- components/badges-section/convention-collectives/index.tsx
- components/etablissement-section/index.tsx
- models/conventions-collectives/index.ts
- models/core/types.ts
- models/core/unite-legale.ts
Improve idcc & summary by adding a title in tooltip
> feat: add title in idcc summary

- app/(header-default)/entreprise/[slug]/_components/effectif-cell.tsx
- components/stats/trafic.tsx
- fix bug effectif cell not displaying `Non renseigné`
- improve wording on stats page
> content: improve user categories

- app/(header-default)/annonces/[slug]/page.tsx
- app/(header-default)/dirigeants/[slug]/page.tsx
- app/(header-default)/donnees-financieres/[slug]/page.tsx
- app/(header-default)/entreprise/[slug]/page.tsx
- app/(header-default)/etablissement/[slug]/page.tsx
- components-ui/alerts-with-explanations/non-diffusible.tsx
- components/donnees-privees-section/index.tsx
- components/non-diffusible-section/index.tsx
- cypress/e2e/fonctionnalites/non-diffusible.cy.js
- cypress/e2e/pages/dirigeants.cy.js
- hide données financières for any non diff
- improve a bit UX and explanations
> feat: hide donnees financieres for non diff

- app/_component/prefetch-dsfr-imgs.tsx
- components-ui/icon/index.tsx
- components-ui/social-media/index.tsx
- components/social-network/index.tsx
- remove twitter/X
- remove facebook
> feat: remove twiiter and facebook links

- clients/api-entreprise/chiffres-affaires/index.ts
- Détails :
- Sort CA from dgfip by year
Closes #1520
> fix: sort ca from dgfip by year

- app/(header-default)/a-propos/comment-ca-marche/page.tsx
- app/(header-default)/accessibilite/page.tsx
- app/(header-default)/formulaire/supprimer-donnees-personnelles-entreprise/_components/connection-france-connect.tsx
- app/(header-default)/vie-privee/page.tsx
- models/constants.ts
- pages/erreur/trop-de-demandes.tsx
- public/acces-refuse.html
- public/recharger-la-page.html
- public/trafic-inhabituel.html
- Détails :
- Remplace l'email de contact par le formulaire de contact
> feat: replace email with contact form

- app/(header-default)/documents/[slug]/_components/conformite/index.tsx
> fix: conformite

- components/section-with-use-case/ask-use-case.tsx
- components/section-with-use-case/index.tsx
> fix: use case form

- app/layout.tsx
- components/banner/nps.tsx
- components/faq-parcours/question.tsx
- utils/headers/content-security-policy.ts
Reverts annuaire-entreprises-data-gouv-fr/site#1583
Merge and deploy when tally form campaign ends
> Remove tally form

- app/(header-default)/annonces/[slug]/_components/bodacc.tsx
Request from support
Compare with current display https://annuaire-entreprises.data.gouv.fr/annonces/797935699
> fix: format date in procedure collectives

- components/api-monitoring/index.tsx
- components/api-monitoring/styles.module.css
Still not the best, but it is an easy improvement that will make life easier for our color blind friends
> feat: improve readibility for color blind

- package-lock.json
- package.json
> chore: bump sentry(dependabot)

- app/(header-default)/dirigeants/[slug]/_component/sections/collectivite/elus-section.tsx
Relates to #868 
https://annuaire-entreprises.data.gouv.fr/dirigeants/200054807
> feat: elus are first sorted by role and then by name

- app/(header-default)/a-propos/equipe/page.tsx
> feat: modify anais

- components-ui/alerts-with-explanations/association-adress.tsx
> fix: add space

- .github/workflows/external-api-test.yml
Following : https://gist.github.com/vansergen/88eb7e71fea2e3bdaf6aa3e752371eb7
> feat: configure Git for commit signing in external API tests

- .github/workflows/ping-seo-repo.yml
- Zones impactées : `.github/workflows/ping-seo-repo.yml`
- Détails :
- Ajout d'un workflow GitHub qui déclenche le workflow SEO
- Ajout d'un secret github actions "GH_PAT_TOKEN" qui permet uniquement de déclencher des workflows sur le repo seo
- Suppression du cron sur le workflow SEO : https://github.com/annuaire-entreprises-data-gouv-fr/seo/pull/20
- NB : à tester quand c'est fusionné 
Closes #1550
> feat: add GitHub Action to ping SEO repository

- clients/_test/clientTVA/index.test.ts
- Détails :
- Set a longer timeout for vat
> fix: increase timeout for clientTVA snapshot tests

- .github/workflows/ping-seo-repo.yml
- Détails :
- improve failed workflow formatting
> fix: improve failed workflow message

- clients/_test/clientTVA/index.test.ts
- Détails :
- Timeout for the tva on external api tests
> fix: disable clientTVA external API tests

- clients/authentication/rate-limiter/index.ts
- Détails :
- Doublage du nombre de requêtes autorisés par jour et par semaine
> feat: update rate limits

- data/changelog.yml
- Détails :
- Mise à jour du changelog avec la limitation du nombre de requêtes
> feat: add data consultation limit for agents on March 18, 2025

- app/(header-compte)/lp/agent-public/page.tsx
Fix typo to ensure consistency with `Site grand public`
> style: add inclusivity to dirigeants

- clients/api-inclusion/inclusion-kind.ts
- clients/api-inclusion/index.ts
- Détails :
- Utilisation du token pour accéder à l'API inclusion en utilisation un header Bearer
> fix: use token for api inclusion

- app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/beneficiaires/index.tsx
- app/(header-default)/documents/[slug]/_components/conformite/index.tsx
- app/(header-default)/documents/[slug]/_components/travaux-publics/index.tsx
- components/section-with-use-case/ask-use-case.tsx
- models/use-cases/index.ts
- Détails :
- Fit our use cases to api entreprises
> refactor: update use cases for public aid across multiple components

- app/(header-default)/dirigeants/[slug]/_component/liens-capitalistiques/index.tsx
- app/(header-default)/dirigeants/[slug]/_component/liens-capitalistiques/protected-liens-capitalistiques-section.tsx
- app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/dirigeants-protected/section.tsx
- app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/summary.tsx
- app/(header-default)/dirigeants/[slug]/page.tsx
- app/(header-default)/donnees-financieres/[slug]/_components/liasses-fiscales/protected-liasses-fiscales-section.tsx
- app/api/data-fetching/routes-handlers.ts
- app/api/data-fetching/routes-paths.ts
- app/api/data-fetching/routes-scopes.ts
- app/api/hide-personal-data/route.ts
- clients/api-entreprise/liens-capitalistiques/index.ts
- clients/api-entreprise/liens-capitalistiques/types.ts
- clients/routes.ts
- components/title-section/tabs/index.tsx
- components/unite-legale-badge/index.tsx
- cypress/fixtures/dgfip-liens-capitalistiques.json
- cypress/mocks/handlers/liens-capitalistiques.ts
- cypress/mocks/routes.ts
- hooks/fetch/use-API-route-data.ts
- models/authentication/agent/scopes/index.ts
- models/authentication/user/rights.ts
- models/core/types.ts
- models/core/unite-legale.ts
- models/espace-agent/liens-capitalistiques/index.ts
- models/rne/types.ts
- utils/helpers/checks.ts
- utils/helpers/formatting/unite-legale-label.ts
- Fonctionnalité
- Détails :
- Ajout des liens capitalistiques de la DGFIP
Closes #1641
> feat: add liens capitalistiques

- app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/summary.tsx
- app/(header-default)/dirigeants/[slug]/page.tsx
- Détails :
- Pas de liens vers liens capitalistiques si pas de droits
> fix: liens capitalistiques link

- data/administrations/inpi.yml
reseting monitoring for RNE as monitor has been rate limited recently
> feat: reset rne monitor

- data/changelog.yml
-  Changement mineur.
- Détails :
> feat: changelog données financières

- data/administrations/inpi.yml
- Détails :
- Mise à jour de la sonde affichée sur le site
> feat: update sonde rne proxy -> site

- components-ui/logo/index.tsx
- components/administrations/administration-description.tsx
- components/footer/index.tsx
- components/section/index.tsx
- cypress/e2e/fonctionnalites/faq.cy.js
- data/administrations/cibtp.yml
- data/administrations/cnetp.yml
- data/administrations/dgfip.yml
- data/administrations/douanes.yml
- data/administrations/fntp.yml
- data/administrations/gip-mds.yml
- data/administrations/insee.yml
- data/administrations/mef.yml
- data/administrations/msa.yml
- data/administrations/opqibi.yml
- data/administrations/probtp.yml
- data/administrations/urssaf.yml
- Détails :
- Following recommandation for logos from Pôle Numérique Inclusif (https://pad.numerique.gouv.fr/4A-DH1IlTdKBYIQZRiBt6Q)
- Improve administration metadata
> feat: use shorter alt for logos

- app/(header-minimal)/formulaire/nps/page.tsx
- components-ui/dual-range-slider/index.tsx
- components-ui/filter-menu/filter-menu.tsx
- components-ui/select/index.tsx
- components/advanced-search/filter-finances.tsx
- components/advanced-search/filter-structure.tsx
- components/advanced-search/search-filters.tsx
- cypress/e2e/recherche/research-advanced.cy.js
- Détails :
- Correctifs sur les labels des inputs
Avant :
Après :
> refactor: improve accessibility and structure of form elements

- components/tva-cell/index.tsx
- cypress/e2e/pages/fiche-resume.cy.js
> feat: stop vat verify temp

- components/tva-cell/index.tsx
- cypress/e2e/pages/fiche-resume.cy.js
This reverts commit 566ec45963e7950fdacc587c96cb27222ed4fdd8.
- Détails :
> Revert "feat: stop vat verify temp (#1728)"

- app/(header-default)/labels-certificats/[slug]/page.tsx
- clients/recherche-entreprise/index.ts
- clients/recherche-entreprise/interface.ts
- components/advanced-search/filter-structure.tsx
- components/badges-section/labels-and-certificates/index.tsx
- components/labels-and-certificates/patrimoine-vivant/index.tsx
- data/administrations/mef.yml
- data/changelog.yml
- models/core/types.ts
- models/search/search-filter-params.ts
- Fonctionnalité
- Détails :
- Ajout du filtre et de la section "Entreprises du patrimoine vivant"
Closes #1739
> feat: add entreprises du patrimoine vivant

- components/advanced-search/filter-structure.tsx
- components/badges-section/labels-and-certificates/index.tsx
- components/labels-and-certificates/patrimoine-vivant/index.tsx
- data/administrations/mef.yml
- data/changelog.yml
- models/search/search-filter-params.ts
- Détails :
- Entreprises du Patrimoine Vivant -> Entreprise du Patrimoine Vivant
Closes #1750
> fix: typo Entreprise du Patrimoine Vivant

- app/(header-default)/donnees/sources/page.tsx
- Détails :
- Link style
Closes #1748
> fix: improve link styling in DataSourcesPage component

- app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/alim-confiance/section.tsx
- app/(header-default)/labels-certificats/[slug]/page.tsx
- clients/api-data-gouv/alim-confiance/index.ts
- clients/api-data-gouv/alim-confiance/interface.ts
- clients/routes.ts
- components/section/data-section/client.tsx
- components/table/full.tsx
- data/administrations/maa.yml
- data/changelog.yml
- hooks/fetch/alim-confiance.ts
- models/administrations/EAdministration.ts
- Fonctionnalité
- Détails :
- Ajout des données de contrôles sanitaires
Closes #1731
> feat: add alim'confiance data

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/proposer-une-amélioration---.md
> [TEAM]Make Robin default assignee in issues

- clients/open-data-soft/clients/entrepreneur-spectacles/index.ts
- components/labels-and-certificates/entrepreneur-spectacles/index.tsx
- cypress/fixtures/entrepreneur-spectacles.json
- models/certifications/entrepreneur-spectacles.ts
closes https://github.com/annuaire-entreprises-data-gouv-fr/site/issues/1769
examples :
* 952252070
* 51464193500044
> fix: update spectacle vivant fields

- app/robots.ts
- pages/erreur/acces-refuse.tsx
- Détails :
- https://support.google.com/webmasters/answer/7440203#indexed_though_blocked_by_robots_txt
Closes https://github.com/annuaire-entreprises-data-gouv-fr/seo/issues/24
> fix: robots.txt

- app/(header-default)/dirigeants/[slug]/_component/sections/entreprise/alim-confiance/section.tsx
- clients/api-data-gouv/alim-confiance/interface.ts
- clients/routes.ts
- Détails :
- Temp hide alim confiance
> fix: temp hide alim confiance

- clients/recherche-entreprise/index.ts
This reverts commit ea86722d9c0a865fad1be6797815dd15ac306865.
- Détails :
> Revert "fix: temp hide alim confiance (#1774)"

- components/etablissement-liste-section/index.tsx
- Détails :
- Cohérence pour établissements en activité
Closes #1756
> fix: update label handling in EtablissementTable component

- components/advanced-search/filter-structure.tsx
- models/search/search-filter-params.ts
- Détails :
- Recherche avec un filtre sur plusieurs labels
Closes #1759
> feat: multi label filter

- components/non-diffusible-section/index.tsx
> chore: update non-diffusible description

- app/api/share/button/[slug]/route.ts
- app/api/share/qr/[slug]/route.ts
- Détails :
- Relatifs aux indexation non voulues dans la search console (ticket SEO)
> feat: add X-Robots-Tag header to share button and QR route responses

- app/(header-default)/export-csv/Filters.tsx
- clients/sirene-insee/build-query.ts
- utils/helpers/formatting/categories-entreprise.ts
> refacto: small sirene.fr improvments

- app/(header-default)/export-csv/ExportCsv.tsx
- app/(header-default)/export-csv/Filters.tsx
- app/(header-default)/export-csv/FiltersSummary.tsx
- app/(header-default)/export-csv/styles.module.css
- components-ui/dual-range-slider/index.tsx
- Détails :
fix: improve download link
fix: jusqu'au date
fix: keep input values when modify filters
fix: handle case with 0 result
fix: use buildQuery for export
feat: disabledColor only for slider
> fix: sirene

- app/(header-default)/export-csv/ExportCsv.tsx
- app/(header-default)/export-csv/Filters.tsx
- app/(header-default)/export-csv/FiltersSummary.tsx
- app/api/export-csv/input-validation.ts
- clients/sirene-insee/build-query.ts
- components-ui/icon/index.tsx
- Détails :
- Ajout du filtre par catégorie juridique
Closes #1831
> feat: sirene.fr add legal categories filter

- app/(header-default)/export-csv/ExportCsv.tsx
- app/(header-default)/export-csv/Filters.tsx
- app/(header-default)/export-csv/FiltersSummary.tsx
- app/(header-default)/export-csv/SiretFilter.tsx
- app/(header-default)/export-csv/styles.module.css
- Détails :
- Ajout d'un filtre par chargement de fichier .txt avec des sirens ou sirets
Closes #1811
> feat: sirene.fr add siren/siret upload

- components/advanced-search/filter-structure.tsx
- components/badges-section/labels-and-certificates/index.tsx
- components/labels-and-certificates/ess/index.tsx
- cypress/e2e/fonctionnalites/dynamic-pages.cy.js
- cypress/e2e/pages/labels-et-certificats.cy.js
- models/search/search-filter-params.ts
> [Filters]chore: rename ess labels

- package-lock.json
- package.json
> feat: update next

- app/(header-default)/export-sirene/ExportCsv.tsx
- app/(header-default)/export-sirene/Filters.tsx
- app/(header-default)/export-sirene/LocationTags.tsx
- app/(header-default)/export-sirene/SiretFilter.tsx
- app/(header-default)/export-sirene/styles.module.css
- clients/sirene-insee/build-query.ts
- components-ui/icon/index.tsx
- Détails :
- V1 final
Closes #1840
> feat: reprise sirene.fr v1 final

- data/administrations/inpi.yml
closes https://github.com/annuaire-entreprises-data-gouv-fr/site/issues/1794
> [FAQ]chore: add etat administratif to faq page

- app/(header-default)/export-sirene/ExportCsv.tsx
- app/(header-default)/export-sirene/Filters.tsx
- app/(header-default)/export-sirene/FiltersSummary.tsx
- app/(header-default)/export-sirene/styles.module.css
- Fonctionnalité
- Détails :
- Filtre ess et société à mission 
Closes #1863
> feat: add filters for ess and societe a mission

- clients/api-d-roles/index.ts
- clients/routes.ts
- models/group/index.ts
- models/groups/index.ts
- Détails :
- Mise à jour des clients d-roles
> chore: update to new d-roles api

- models/groups/index.ts
This reverts commit 166a8b563594e0bfa5220bb1ff078f27f8001a4e.
- Détails :
> Revert "fix: log d roles client id to sentry (#1861)"

- components-ui/full-screen-modal/index.tsx
- components/espace-agent-components/add-user.tsx
- components/espace-agent-components/group-entity.tsx
- components/espace-agent-components/group-management.tsx
- components/espace-agent-components/update-name.tsx
- components/welcome-modal-agent/index.tsx
- Détails :
- Appuyer sur Entrée pour valider une modale
- Cacher le bouton pour actualiser le nom d'un groupe si l'utilisateur n'est pas admin
- Afficher un message si l'utilisateur n'appartient à aucune équipe
> Fix d role front

- app/(header-default)/export-sirene/page.tsx
temporary redirect to / when trying to visit siren page
> [BUG]chore: deactivate export sirene

- app/(header-compte)/compte/mes-equipes/page.tsx
- components/espace-agent-components/agent-navigation.tsx
- components/espace-agent-components/group-management/group-item.tsx
- components/espace-agent-components/group-management/update-modals/update-user.tsx
- components/header/menu/index.tsx
related to https://github.com/annuaire-entreprises-data-gouv-fr/site/issues/1890
> [EspaceAgent]style: fix typos in Mes groupes page

- app/(header-compte)/compte/accueil/page.tsx
- app/(header-compte)/compte/mes-groupes/page.tsx
- components/espace-agent-components/agent-navigation-link.tsx
- components/espace-agent-components/agent-navigation.tsx
- components/header/menu/index.tsx
- cypress/support/commands.ts
- models/authentication/agent/index.ts
- models/authentication/user/rights.ts
- Détails :
- Ouverture des groupes pour tous les agents
> feat: enable groups to every agent

- app/api/groups/route-wrappers.ts
- clients/roles-data/client.ts
- clients/roles-data/index.ts
- clients/roles-data/interface.ts
- clients/routes.ts
- components/espace-agent-components/group-management/group-item.tsx
- components/espace-agent-components/group-management/index.tsx
- components/espace-agent-components/group-management/update-modals/add-user.tsx
- components/espace-agent-components/group-management/update-modals/delete-user.tsx
- components/espace-agent-components/group-management/update-modals/update-user.tsx
- models/authentication/group/groups.ts
- models/authentication/group/index.ts
- models/authentication/group/roles.ts
- models/espace-agent/utils.ts
Refactor DRoles into roles.data
> refactor: rename roles.data

- models/authentication/habilitation/index.ts
> feat: update contract url and contract description

- app/(header-compte)/compte/accueil/page.tsx
- style/globals.css
Freely inspired by @renardpal mock up
references #1896
> feat: add link to datapass form, for admin only

- models/core/diffusion/index.ts
title self explainatory.
Shoud be reverted in #1955
closes #1951
> feat: hide 851915207

- clients/sirene-insee/build-query.ts
- clients/sirene-insee/export-csv.ts
- Détails :
- Suite à l'email de l'INSEE, suppression des champs inutiles dans l'export
> feat: remove deprecated field from sirene.fr export

- package-lock.json
- package.json
-  Changement mineur.
- Détails :
- Bump Next
> chore: bump next

- app/(header-compte)/compte/habilitation/[demandeId]/succes/page.tsx
related to https://github.com/annuaire-entreprises-data-gouv-fr/site/issues/1963
> [EspaceAgent]fix: typo in group validation page

- .github/workflows/deploy.yml
> Revert CI changes (staging deploy)

- .env.dev
- app/api/auth/france-connect/callback/route.ts
- clients/authentication/france-connect/strategy.ts
- Détails :
- Update france connect version
Closes #1880
> feat: update to last version of france connect

- .env.dev
- app/api/auth/france-connect/callback/route.ts
- clients/authentication/france-connect/strategy.ts
This reverts commit b9d2aaec35ec1ecadfad69c3ce7ff83b1f2576b2.
- Détails :
> Revert "feat: update to last version of france connect (#1915)"

- app/api/export-csv/route.ts
- clients/sirene-insee/export-csv.ts
- models/sirene-fr/index.ts
- utils/network/index.ts
- Détails :
- Use stream
Closes #1931
> feat: use stream for sirene-fr

- components/banner/nps.tsx
- Détails :
- Gestion du cas où Tally est undefined (problème réseau par exemple)
> fix: tally undefined

- app/layout.tsx
- components/banner/nps.tsx
- utils/headers/content-security-policy.ts
- Détails :
- Suppression du lien Tally temporaire
> Revert "feat: add tally (#1993)"

- clients/matomo/index.ts
- Détails :
- Suite à la mise à jour de Matomo, utilisation du token pour toutes les routes
> fix: use matomo token for every routes

- components/header/header-core/index.tsx
- components/notification-center/styles.module.css
- Correction d'un bug. 
- Détails :
- Correction d'un bug d'affichage du menu sur mobile
Closes #2006
> fix: menu mobile doesn't work

- app/(header-default)/export-sirene/Filters.tsx
- app/(header-default)/export-sirene/styles.module.css
- Détails :
- Amélioration de la responsivité de l'export sirene
> fix: improve responsivity for export-sirene

- data/faq/extraire-liste-entreprises.yml
- Détails :
- Mise à jour faq avec export sirene
- 
Closes #2016
> feat: adapt faq to export sirene

- data/administrations/dgfip.yml
- Zones impactées : page Sources des données.
- Détails :
- Ajout de Liens capitalistiques
related to #2047
> feat(sources): adds Liens capitalistiques to sources
